### ISSUE TITLE
Install on mac os x?

### ISSUE THREAD

**Issue by cby016** [kevinvincent/ha-wyzesense#10]
I tried installing this on my mac mini and I don't see the /dev/hidraw* device. Does anyone know the correct usb path on mac?

**Comment by kevinvincent** [comment]
Unfortunately this is unsupported on MacOS. MacOS does not provide applications direct access to hidraw devices. I tried developing it on my mac first and found this out. Sorry!

**Comment by cby016** [comment]
No worries. Looks like I might have to move HA to another box or wait for an official integration. Thanks for your work on this!
