### ISSUE TITLE
Scan completed with no sensor found.

### ISSUE THREAD

**Issue by sanmagal** [kevinvincent/ha-wyzesense#103]
I´ve got my HA running on a RPi. The Scan service seems to be working: when calling the service the receiver starts blinking but I´m not able to pair any of the sensors. Even thow the red led blinks 3 times I always get the notification " Scan completed with no sensor found."

**Comment by VarenDerpsAround** [comment]
You used the tool in the box for the sensor to press into the little hole in the bottom for 3 seconds? Using that tool, for 5 seconds on the sensor, will make the sensor blink 3 times red, then you know you can pair them. You have to do them relatively at the same time, but yea, the sensors need to be put into pairing mode too.

**Comment by sanmagal** [comment]
I´ve used the tool and the sensor led blinks red 3 times but still I get the notification "Scan completed with no sensor found."

**Comment by VarenDerpsAround** [comment]
Hmm, is the sensor near the hub? What is the position of the hub in the home compared to the sensor? Is it possible it's already linked? I'm not really sure bud, could be a couple things.

**Comment by sanmagal** [comment]
The same thing happens with the wyze app. The receiver blinks and th ewyze cam says it is ready to connect but the connection times out without success.

**Comment by photinus** [comment]
Sounds like you might have a bad dongle or sensors, try contacting Wyze
support for a RMA?

**Comment by sanmagal** [comment]
Donne that. waiting for feedback

Sanches Magalhães 
urologiasanchesmagalhaes.pt
www.linkedin/in/sanchesmagalhaes


> No dia 09/02/2020, às 17:07, Will McCloskey <notifications@github.com> escreveu:
> 
> ﻿Sounds like you might have a bad dongle or sensors, try contacting Wyze
> support for a RMA?
>

**Comment by costr** [comment]
For what it's worth; I was running into this issue as well. Another symptom that I had was that the receiver was showing an orange/yellow LED status most of the time.

It seems that my issue was that my Raspberry Pi 3 was under voltage. I used an appropriate power cable to fully test and so far so good. My devices have been added, are responsive, and the receiver shows a blue status LED constantly.

I'll update again if the symptoms return.

**Comment by keith10247** [comment]
Started running in to this issue after the latest update of HA.  Tried reinstalling WyzeSense and still have the issue.  Tried 2 different motion sensors and they both flash the red light but the scan says they come back with no new sensors.  Old sensors work fine still.  I attempted to move them super close to the sensor and it still doesn't catch them.   Receiver has a solid blue (except for when it flashes when I run the scan).  Anyone else having this issue?

**Comment by photinus** [comment]
Seems like a hardware issue, not something we can fix in code

**Comment by jshayden** [comment]
> I´ve got my HA running on a RPi. The Scan service seems to be working: when calling the service the receiver starts blinking but I´m not able to pair any of the sensors. Even thow the red led blinks 3 times I always get the notification " Scan completed with no sensor found."

I had this same issue. I fixed it by holding the button on the front of the receiver for 10s. Light started flashing orange/blue again. Ran the scan service, and things started working.

**Comment by shankerrhce** [comment]
how to run the scan command on HA
