### ISSUE TITLE
Are the sensors still visible to wyzes app?

### ISSUE THREAD

**Issue by yfaber** [kevinvincent/ha-wyzesense#104]
Are the sensors still supposed to show on wyze's app? can I keep the hub connected to the camera or i need to plug it into my Pi4?

**Comment by photinus** [comment]
No, the dongle has to be plugged into your home assistant system and as a
result will no longer be available in the wyze app

**Comment by jfarmer08** [comment]
Try this one: https://github.com/JoshuaMulliken/ha-wyzeapi
