### ISSUE TITLE
Active USB Cable

### ISSUE THREAD

**Issue by 4x4ff** [kevinvincent/ha-wyzesense#105]
Does this work if you are using an active usb cable to plug the Wyze receiver into?  I need to change the location of my machine and will increase the distance from my devices to the receiver and though this might be a good alternative to remotely locate the receiver.

**Comment by biga888** [comment]
I am using a 6 ft USB extension cord and it works fine.

**Comment by 4x4ff** [comment]
Thanks for the reply.  I was leaning towards a little longer cord....maybe 16 or 32 ft.  Thats why I was leaning towards an active cable.  Just curious if it worked before I bought one.

**Comment by biga888** [comment]
I don't see why not as it is not a high speed device.
I could try putting a few cables together to test, will try and do that
tonight if someone else does not answer.

Cheers.

**Comment by 4x4ff** [comment]
Thanks for the help.  Like I said I want to relocate my HA server and where I move it will be the opposite end of the house from where the sensors are located.  I have a couple that are already at their limits so I figured with a longer cord I can relocate the senor somewhere up in the ceiling (server located in basement).  Please let me know what you find out.

**Comment by biga888** [comment]
I tested with 3 cables connected for a total of 15 ft and worked with no
issues.

**Comment by 4x4ff** [comment]
Fantastic!!!....Thank You very much!!!!!

**Comment by 4x4ff** [comment]
Just for anyones info....I have tested the wyze sensor hooked to a 32' active USB cable and it works perfectly for remotely locating it.

**Comment by biga888** [comment]
Great to hear from you on this! Awesome
