### ISSUE TITLE
State not updating

### ISSUE THREAD

**Issue by dylanmcdermott** [kevinvincent/ha-wyzesense#106]
I've installed the add on and identified the sensors, but the sensor states are not updating at all. What am i missing? I also dont see anything in the logs?

**Comment by VarenDerpsAround** [comment]
What are the states of the devices stuck in? If they are stuck in the on open/motion position, you may need to set their initial state in your config (seen below.) You find the sensor code in the developer options for each sensor. If they are stuck closed, what are the rssi's of the sensors? Lower is better. I'd also suggest doing a clean hassio.host_reboot and seeing if the problem persists. I'm not the repo owner, I just have a lot of sensors, and I'd love to help this integration developer any way I can. His repo is fantastic, I love my wyze sensors. ALSO Recently there was an update that required retriggering each sensor, it could also potentially be that. Essentially, after this latest update you had to retrigger the sensors to get them to sync with the hub. Hope this helps.


```
- platform: wyzesense
    device: auto
    initial_state:
      779B1E20: "off"
      7789BC5B: "off"
      779B14AE: "off"
      779B1DCE: "off"
      779B1E23: "off"
      779B151F: "off"
      779B1577: "off"
      779B192C: "off"
      779B1629: "off"
      .......
      ......

**Comment by drinsmith1** [comment]
I'm having the same issue. Can you define "retrigger" please? Is this as simple as physically opening and closing each switch, or do I need to re-add each sensor to HA?

Thanks!
