### ISSUE TITLE
Sensor stop responding, partially, or completely

### ISSUE THREAD

**Issue by mrsnyds** [kevinvincent/ha-wyzesense#117]
I'm not sure my report will add any new insights, as it seems the root cause is somewhat understood as the OS losing connectivity with the USB device, but I wanted to log the specifics, in case they would help.   (And by the way, kudos and appreciation for the work you and others have done on this component!)

I am using an RPI4, latest HASS OS v3.12, with Home Assistant Core v. 0.107.0.

HomeAssistant WYZE sensors will stop updating.   Sometimes just the motion sensors, and sometimes all of them.   A restart of the application will (on rare occasion) resolve the issue, but most often a reboot is needed.  Sometimes even that will not resolve the issue, and I need to power down and - just for good measure - unplug and replug in the Wyze USB hub.  It does indeed seem as though the OS "loses" the hub, but a cold start always brings everything back.  

To save time and get the sensors doing there job again, I most often will just go right to the power down option.  

Here is my log:  https://pastebin.com/Ldyn9Cmf

**Comment by RonSpawnson** [comment]
Hi mrsnyds - based on discussion in another issue, there is beginning to be a suspicion that an upgrade of the wyze bridge firmware to version 0.33 resolves this issue. This firmware update can be accomplished by plugging into a wyze cam. Anecdotally this has appeared to have resolved the issue for most.

Further discussion is here: https://github.com/kevinvincent/ha-wyzesense/issues/114

**Comment by mrsnyds** [comment]
Hi RonSpawnson - thanks for that suggestion.  I did the firmware update, re-scanned for all of my sensors, and so far so good.   I will reply back to this issue once some time has passed and I can judge the stability over a few days.  It was invariably failing for within one day or two, so it shouldn't take too long for me to answer back on this issue.

**Comment by bschatzow** [comment]
Is there a way to upgrade the firmware without a camera?

**Comment by krupaldesai** [comment]
> Is there a way to upgrade the firmware without a camera?

I too looking forward to know this. Looks like there are others like me who invested in sensors but not camera 🔢.

**Comment by mrsnyds** [comment]
I am now three days into running with the updated firmware and so far have not had a single lapse in the sensors responding.   The firmware updates seems to have done the trick.  I'll try to go a few days straight without a restart (I am usually tinkering with HA), and if still all good I'll close this.

**Comment by mrsnyds** [comment]
I can confirm that this component has remained stable since updating the wyze bridge firmware to version 0.33.
