### ISSUE TITLE
motion sensor sensitivity

### ISSUE THREAD

**Issue by yfaber** [kevinvincent/ha-wyzesense#124]
any chance we can manipulate the sensor sensitivity so it doesn't catch my dog's movement when we are out.

**Comment by RonSpawnson** [comment]
Wyze does not allow modification of sensitivity. See this thread for some suggestions on things you could try (such as electrical tape over portions of sensor). https://www.reddit.com/r/wyzecam/comments/bj4bds/wyze_sense_motion_sensitivity/

**Comment by photinus** [comment]
Limitation of the hardware.
