### ISSUE TITLE
Motion/Door Sensors - Stuck

### ISSUE THREAD

**Issue by bbalz** [kevinvincent/ha-wyzesense#125]
It seems with the last few updates to Home Assistant that the motion/door sensors are getting stuck in an 'on' state or just stuck in general.

I rebooted HA in the past and it seems to take care of it.  However as of today it seems like they just stay in one state and stick.  A reboot doesn't fix it at all.

Currently running HA version 0.108.9.

I didn't see anything specifically in the logs that stood out to me but if I should be looking specifically somewhere please let me know and I'll dig further.

Has anyone else run into an issue with their motion/door sensors with recent updates of HA?

**Comment by drphungky** [comment]
Why was this closed? Was there a solution? I'm having the same issue.
