### ISSUE TITLE
Wyze Sense Repository not loading

### ISSUE THREAD

**Issue by rainiur** [kevinvincent/ha-wyzesense#126]
Running hass.io on Rasp 4 with .109 unable to find the repository.json file.

20-04-30 02:50:55 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/b6c2f286/repository.json: [Errno 2] No such file or directory: '/data/addons/git/b6c2f286/repository.json'

**Comment by VarenDerpsAround** [comment]
How are you adding it to hacs?

**Comment by rainiur** [comment]
Totally a mistake on my part I am new to Home Assistant and a lot of the videos and documentation seem to be irrelevant. I was understanding it was to be loaded with the ADD-ONs not a separate integration. I am attempting to load through HACS now and am looking forward to the integration.
