### ISSUE TITLE
pi 4 docker home assistant 97.2

### ISSUE THREAD

**Issue by osborne82** [kevinvincent/ha-wyzesense#13]
just got my sensor pack but struggling with the usb dongle im not getting any lights 
dmesg | grep hidraw  shows the dongle as hidraw2 so i have that in my config, installed the component via hacs and rebooted several times , i did once get a blue light to show momenteraily but then it went off. 
it would appear the component isnt loading as i see lots of _DoCommand errors 
`

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
timezone | Europe/London
version | 0.97.2
virtualenv | false

`
[home-assistant.log](https://github.com/kevinvincent/ha-wyzesense/files/3505676/home-assistant.log)

**Comment by kevinvincent** [comment]
Hmm, interesting... This looks like its gonna be a hard one. You mentioned that there are no lights, not even orange or white?

**Comment by kevinvincent** [comment]
I've got some ideas on how to fix it, might involve some code changes to the upstream library I'm using to communicate with the device. Expect it to take about day.

**Comment by stoneobscurity** [comment]
you have to pass the usb ports to the docker container in the run line.

 --device=/dev/hidraw0

**Comment by kevinvincent** [comment]
@osborne82 Please update your component, I released a change a few minutes ago that could help with some startup issues and log usb device issues better to aid in debugging.
