### ISSUE TITLE
Door sensors after battery swap are added with no MAC (or MAC 00000000)

### ISSUE THREAD

**Issue by CorneliousJD** [kevinvincent/ha-wyzesense#134]
I happen to have two door sensors that have both had their batteries swapped with brand new Energizer branded batteries. 

Upon adding both of them now to this integration, they are both showing up with a no MAC address or a MAC of 0 or "\0\0\0\0\0\0\0\0" depending on where you look. 

I know there's some other comments out there stating that this is likely because of a faulty sensor, but I do find it hard to believe that both of my door sensors are now faulty after a battery swap on them and they are adding here with no MAC detected.

```
Sensor found and added as: binary_sensor.wyzesense_ (unless you have customized the entitiy id prior).
To add more sensors, call wyzesense.scan again.

More Info: type=1, version=16
```

Since I have two I did try this comment https://github.com/kevinvincent/ha-wyzesense/issues/130#issuecomment-624960162

However while that worked to add one sensor with no MAC, it did not allow me to add another one, the 2nd one just overwrote the original one with no MAC completely. 

This does seem to be a bigger issue or maybe a regression since so many other users recently are reporting the same thing? 

I also do not know how to remove these bad sensors from my HomeAssistant now either. 

Any advice or help is appreciated!

EDIT: I have tried to downgrade to 0.0.6 but for some reason the entire scan/remove services are missing somehow? Not sure why that's happening but I cannot even try adding them on 0.0.6, bummer.

**Comment by CorneliousJD** [comment]
I did find that if you run the service to remove a sensor and for the data you put in 

`mac: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"`

It still showed up in my entities, but after restarting HA I could then finally delete it. It seems like it's actually finally gone now, but would still like to get to the bottom of what's going on.

Sadly in troubleshooting this thinking the battery connection wasn't good enough on one of them I broke off a part that connects the battery, so one of the two sensors I have is now dead because of that. Whoops.

I do have 4 more brand new sensors on the way if USPS can find them and actually get them delivered to me. Will hope that those 4 work correctly, but if there's anything I can do to fix the one bad one I still have or anything you need me to do to test, let me know. Thanks.

**Comment by McNutty195** [comment]
I am also having this problem. I tried you're suggestion above to remove the sensor and was successful. However, when I try scanning it back in it just pops up the same way it was before. Is it possible that we could hard reset the sensor itself somehow? Like you, the problem appeared as soon as a swapped the batteries on the sensor. Just throwing mud at the wall.

**Comment by firestrife23** [comment]
Some ideas to try, how about adding sense sensors to wyze app and it may help by restoring it back to factory setting that way, then remove it from wyze app and re-add to HA. I haven't tried it myself but I think it's worth a shot.

**Comment by McNutty195** [comment]
> Some ideas to try, how about adding sense sensors to wyze app and it may help by restoring it back to factory setting that way, then remove it from wyze app and re-add to HA. I haven't tried it myself but I think it's worth a shot.

Yeah, I had a similar thought and tried that. Didn't work in my case sadly. I ended up contacting Wyze and they replaced them for free. The new ones work fine. Seems like it is some kind of hardware defect.

**Comment by turbo4door** [comment]
> > Some ideas to try, how about adding sense sensors to wyze app and it may help by restoring it back to factory setting that way, then remove it from wyze app and re-add to HA. I haven't tried it myself but I think it's worth a shot.
> 
> Yeah, I had a similar thought and tried that. Didn't work in my case sadly. I ended up contacting Wyze and they replaced them for free. The new ones work fine. Seems like it is some kind of hardware defect.


Did you mention that you were using it through Home Assistant? I don't have them paired to my Wyze app so I won't be able to do any of their troubleshooting if required I guess.

**Comment by McNutty195** [comment]
> > > Some ideas to try, how about adding sense sensors to wyze app and it may help by restoring it back to factory setting that way, then remove it from wyze app and re-add to HA. I haven't tried it myself but I think it's worth a shot.
> > 
> > 
> > Yeah, I had a similar thought and tried that. Didn't work in my case sadly. I ended up contacting Wyze and they replaced them for free. The new ones work fine. Seems like it is some kind of hardware defect.
> 
> Did you mention that you were using it through Home Assistant? I don't have them paired to my Wyze app so I won't be able to do any of their troubleshooting if required I guess.

I honestly don't remember if I mentioned using home assistant. I don't think I did. They asked me to do a few rounds of connection, and reset through the wyze app with the bridge connected to a camera. I played along with this by temporarily disconnecting the bridge from home assistant and connecting it to a camera. The sensors didn't work this way either, so after a couple different troubleshooting steps they said they were defective and that they'd send new ones out free of charge. Hope that helps!

**Comment by smnino** [comment]
> The sensors didn't work this way either, so after a couple different troubleshooting steps they said they were defective and that they'd send new ones out free of charge. Hope that helps!

Did you have any luck with the replacement sensors? I have experience the exact same as you describe. Sensors that worked fine suddenly don't. Seems odd the sensors (multiple) go bad all of the sudden and at the same time.

**Comment by McNutty195** [comment]
> > The sensors didn't work this way either, so after a couple different troubleshooting steps they said they were defective and that they'd send new ones out free of charge. Hope that helps!
> 
> Did you have any luck with the replacement sensors? I have experience the exact same as you describe. Sensors that worked fine suddenly don't. Seems odd the sensors (multiple) go bad all of the sudden and at the same time.

I agree that it seems rather odd that multiple went bad around the same time, though for me it seemed to center around replacing the batteries. The replacement sensors have been working fine since I received them which has been a while ago now.

**Comment by BrewNinja** [comment]
Just an FYI, this is a known issue with the sensors. If you let the battery get too low, it will cause the sensor to lose its mac address. Stupidest design decision ever. We just need to figure out how to re-provision a mac for the devices that lost them. Anyways, not an issue with the integration, but with the hardware. See the warning message here: https://support.wyzecam.com/hc/en-us/articles/360031022231-How-long-does-the-sensor-s-battery-last-

**Comment by CorneliousJD** [comment]
Wow, the fact that they're actually acknowledging this is intresting. Serious design flaw with these things. I hope they sort it out as to why and then ship free replacements to everyone who has dead sensors. They replaced a few of mine so far without an issue but I have like 12 sensors so it's only going to keep happening :( 

Closing this then with the suggestion to contact their support as it's NOT an issue the integration, but rather a Wyze issue altogether.

Would recommend everyone setup some sort of template value or Node-RED notification trigger that when the battery is low enough you get a warning to replace it. :) 

![image](https://user-images.githubusercontent.com/724777/92730694-24dbd800-f342-11ea-887b-c575b8a1918d.png)

**Comment by PierreScerri** [comment]
The last reported battery level on all my sensors is above 80%.  And 3 of them have a low battery (LED flashes every 10 seconds or so).
So there is no point in checking for a low battery level because it will never trigger.

**Comment by wct0791** [comment]
That was what I was wondering about. I’d kept a decent watch on the battery levels and never worried about their numbers. Then suddenly 3 of my contact sensors died and the missing MAC addresses led me here.

**Comment by PierreScerri** [comment]
And the odd thing is that when I add them again they attach themselves to the first sensor that had its battery replaced.  This makes both sensors work on the same window.  Adding the MAC address to the first one does not help as it is removed once the second sensor is added.

**Comment by BrewNinja** [comment]
80 is way too low. Try like 85. Also, unless you trigger the sensor occasionally, it wont send back any data on the battery level. I have notifications setup for both how long its been, and battery level. 

@PierreScerri There is no MAC address, it lost it. So its new MAC is essentially "NULL" So when you add the second one, it also says, "Hi, my MAC is 'NULL'" and now you have 2 sensors that think they are the same person. Once they lose their MAC, they are essentially worthless since they cant be differentiated between.

**Comment by turbo4door** [comment]
I told them I used them ONLY through home assistant. They replaced with no
issue just took them a few to understand how I used them and that the
failure was not related to how they were being used.

**Comment by PierreScerri** [comment]
What is the support email address of Wyze?  support@wyze.com is not monitored.  And I can't call as the stupid bot suggests.

**Comment by PierreScerri** [comment]
@CorneliousJD Would you let me have one of those flows for checking the battery level please?
Thanks.

**Comment by CorneliousJD** [comment]
> @CorneliousJD Would you let me have one of those flows for checking the battery level please?
> Thanks.

@PierreScerri 

So I'm not sure how off hadn to export just one line of this flow but here's screenshots that should let you easily replicate it.

![image](https://user-images.githubusercontent.com/724777/96003385-2cdadc00-0e08-11eb-8677-043709a5a87a.png)
![image](https://user-images.githubusercontent.com/724777/96003421-349a8080-0e08-11eb-9b66-45c04693bcfd.png)
![image](https://user-images.githubusercontent.com/724777/96003473-40864280-0e08-11eb-9f9b-bbfed837df87.png)
![image](https://user-images.githubusercontent.com/724777/96003495-467c2380-0e08-11eb-8a42-a38dcbbb66cf.png)
![image](https://user-images.githubusercontent.com/724777/96003525-4d0a9b00-0e08-11eb-8303-e9daf44760d5.png)
![image](https://user-images.githubusercontent.com/724777/96003563-572c9980-0e08-11eb-8dbd-204dcd8f0b24.png)
![image](https://user-images.githubusercontent.com/724777/96003576-5d227a80-0e08-11eb-8295-8c635165d461.png)

**Comment by PierreScerri** [comment]
Thanks a lot.  That is very helpful.

**Comment by PierreScerri** [comment]
I have used your idea as follows:
![Screenshot 2020-10-14 at 19 29 17](https://user-images.githubusercontent.com/34303331/96024337-e1e6b600-0e53-11eb-9f41-50f9a390dbe1.png)

- Inject node triggers at noon each day.
- Get Entities node catches all binary_sensors.
- First switch node allows only entities that are windows. You can add more types here (e.g. _motion)
- Second switch node catches battery levels <85.
- Call service node sends a notification for each window with the battery level.

![Screenshot 2020-10-14 at 19 26 21](https://user-images.githubusercontent.com/34303331/96024504-1bb7bc80-0e54-11eb-8e92-979feefd4820.png)
![Screenshot 2020-10-14 at 19 26 39](https://user-images.githubusercontent.com/34303331/96024507-1ce8e980-0e54-11eb-9eb9-8bf8b0a8b925.png)
![Screenshot 2020-10-14 at 19 26 47](https://user-images.githubusercontent.com/34303331/96024513-1d818000-0e54-11eb-9cc8-dcbb1c0f7a70.png)
![Screenshot 2020-10-14 at 19 27 38](https://user-images.githubusercontent.com/34303331/96024514-1e1a1680-0e54-11eb-8e21-e12238e4a9f2.png)
![Screenshot 2020-10-14 at 19 38 03](https://user-images.githubusercontent.com/34303331/96024971-ce881a80-0e54-11eb-94ea-f6348b4ba8fb.png)

One flow to rule them all!

**Comment by PierreScerri** [comment]
@BrewNinja . I've got the battery level figured out.  How do you handle the '...how long it's been...' part?

> 80 is way too low. Try like 85. Also, unless you trigger the sensor occasionally, it wont send back any data on the battery level. I have notifications setup for both **how long its been**, and battery level.
> 
> @PierreScerri There is no MAC address, it lost it. So its new MAC is essentially "NULL" So when you add the second one, it also says, "Hi, my MAC is 'NULL'" and now you have 2 sensors that think they are the same person. Once they lose their MAC, they are essentially worthless since they cant be differentiated between.

**Comment by BrewNinja** [comment]
You would need to do something off of timestamp. I just have a card in my dashboard that shows me the last timestamp, but if you want to put it in a flow/automation, then you would need to calculate how long its been since the timestamp.

**Comment by 1h8fulkat** [comment]
> * Get Entities node catches all binary_sensors.

Very nice flow!  Worth noting that the Get Entities node needs to have an output type of Split and not the default of Array.   Took me a minute to find that setting.

**Comment by PierreScerri** [comment]
@1h8fulkat Thanks. Much better than having a dozen identical flows.  Makes editing much easier.

Sorry about the 'Get entities' bit; the screen grab was too short.  

But yes, you're right the output is split not array.
