### ISSUE TITLE
Renamed component in HASS v0.110

### ISSUE THREAD

**Issue by worf-nm** [kevinvincent/ha-wyzesense#138]
After upgrading to v0.110 the following warning appears in the logs:

 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify WyzeSensor to extend BinarySensorEntity

This seems to have been caused by https://github.com/home-assistant/core/commit/b022e08db9b722af39fe34ebd543d81be8e1744d#diff-3d99deefc08c356e814e2f36025af012

Good thing it still works although not sure when the logic will be filly switched.

**Comment by photinus** [comment]
Fixed in latest master.
