### ISSUE TITLE
Platform not found: binary_sensor.wyzesense

### ISSUE THREAD

**Issue by photinus** [kevinvincent/ha-wyzesense#14]
Tried installing through HACS and Manually, get the same result both time, when I do a check config, I get the error:

Platform not found: binary_sensor.wyzesense

I used HACS to install the integration and then restarted HA, tried adding the configuration to my config file and go the error on config check.

HA Version: 0.96.0
Log: https://pastebin.com/v7YeZKCU

arch | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
timezone | America/Los_Angeles
version | 0.96.0
virtualenv | false

 dmesg | grep hidraw
[    1.122271] hidraw: raw HID events driver (C) Jiri Kosina
[    2.404180] hid-generic 0003:0E0F:0003.0001: input,hidraw0: USB HID v1.10 Mouse [VMware VMware Virtual USB Mouse] on usb-0000:02:02.0-1/input0
[    2.423103] hid-generic 0003:0E0F:0003.0002: input,hidraw1: USB HID v1.10 Mouse [VMware VMware Virtual USB Mouse] on usb-0000:02:02.0-1/input1
[    4.237589] hid-generic 0003:1A86:E024.0003: hiddev96,hidraw2: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:02:02.0-2.2/input0
[  188.026839] hid-generic 0003:1A86:E024.0004: hiddev96,hidraw2: USB HID v1.00 Device [HID 1a86:e024] on usb-0000:02:02.0-2.2/input0

Config:
binary_sensor:
  - platform: wyzesense
    device: '/dev/hidraw2'

**Comment by mediacowboy** [comment]
Maybe Kevin can help but I'm not seeing any issues.

**Comment by photinus** [comment]
After bashing my head on the wall, got it working, Not sure what I did, but I upgraded to HA .97.2 in the process and the latest HACS as well.

**Comment by kevinvincent** [comment]
Does it work consistently now? Or is it flakey on restarts?

**Comment by photinus** [comment]
Closing as it's been stable and not able to reproduce anymore
