### ISSUE TITLE
BinarySensorDevice is deprecated

### ISSUE THREAD

**Issue by B3voholic** [kevinvincent/ha-wyzesense#143]
Getting the following error in the logs after updating to 110.

2020-05-23 18:08:58 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify WyzeSensor to extend BinarySensorEntity

I don't have anything specifically called these in my configs anywhere.  Does anyone have any idea what this is?

**Comment by SupahNoob** [comment]
The deprecating warning is referencing that actual wyze sensor that's exposed to Home Assistant. [[here](https://github.com/kevinvincent/ha-wyzesense/blob/master/custom_components/wyzesense/binary_sensor.py#L187)]

Addressed in a blog post from earlier this month - essentially some hass internals had a change which should be a simple update for @kevinvincent. 

https://developers.home-assistant.io/blog/

**Comment by photinus** [comment]
This is already fixed in in the current release.
