### ISSUE TITLE
Error...wyzeplatform...binary_sensor

### ISSUE THREAD

**Issue by welbo97** [kevinvincent/ha-wyzesense#148]
HA 0.110.4, HassOS 4.9, proxmox VM, ha-wyzesense 0.08

HACS for ha-wyzesense setup, previously working (very well, thank you!)

Found similar issue: [#131 ](https://github.com/kevinvincent/ha-wyzesense/issues/131)
After some restarts, I found my binary_sensors for wyze components showing as "Unavailable" in the UI. I found some errors in the logs (did not copy them) and tried uninstalling the HACS addon, restarting, reinstalling and restarting again. The sensors are still unavailable and this error is found in the logs after each restart:
```2020-06-06 15:12:33 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up wyzesense platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 78, in setup_platform
    _LOGGER.debug("Attempting to open connection to hub at " + config[CONF_DEVICE])
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by hfcheng66** [comment]
saw this error as well. 
Home Assistant 0.110.5

**Comment by hfcheng66** [comment]
fixed it. it turns out the bridge is not working. unplug it and plug it back, restart hass and it works fine now.

**Comment by jamescadd** [comment]
@welbo97 I'm starting to wonder if ProxMox is the common denominator here.  Same issue for me.

**Comment by welbo97** [comment]
> @welbo97 I'm starting to wonder if ProxMox is the common denominator here. Same issue for me.

I found the ```hidrawX``` device had changed and was not being properly passed through proxmox. Once I addressed that problem, it started working again without repairing the sensors.
