### ISSUE TITLE
Can't add repository, throws error

### ISSUE THREAD

**Issue by meyerdenney** [kevinvincent/ha-wyzesense#158]
When I add the repository to the Add-on store it doesn't show up. Any thoughts on what the solution might be?

When I look in the system logs I see:

```
20-07-02 23:51:12 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/kevinvincent/ha-wyzesense repository
20-07-02 23:51:13 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/6cc4096c/repository.json: [Errno 2] No such file or directory: '/data/addons/git/6cc4096c/repository.json'
20-07-02 23:51:13 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/6cc4096c/repository.json
```

I'm on version 0.112 of HA and Supervisor version 3.13

**Comment by VarenDerpsAround** [comment]
are you adding it in hacs?

**Comment by meyerdenney** [comment]
> are you adding it in hacs?

I added it in Supervisor > Add-on Store > Triple dot menu in top right > this dialog 
![image](https://user-images.githubusercontent.com/1121461/86493686-4491c700-bd27-11ea-8afb-1adae94a7f4b.png)

I've already installed hacs via their shell script and I can see the hacs folder under /config/custom_components/
I also tried manually adding the wyzesense files to /config/custom_components/ via the manual instructions but I don't see the wyze scan service or the bridge entity.

I'm on OS v 3.13 - for some reason I can't upgrade to the latest version of 4.10

**Comment by meyerdenney** [comment]
Ahh, I didn't finish the install steps for HACS, I merely copied over the files to /config/custom_components/. I was able to add this repo just fine and install the Wyze Sense Component. Closing issue. Thanks!!
