### ISSUE TITLE
HIDRAWxx changes between reboots

### ISSUE THREAD

**Issue by bronder** [kevinvincent/ha-wyzesense#161]
I'm not sure this is an issue with the add-on or my lack of understanding Linux.  But when I started I put the configuration on hidraw0 and everythign was great.  Then I rebooted and everything was unavailable.  After a bit of debugging I notice that the usb dongle is at times on hidraw0 and at times hidraw1.  Any idea how I can force this to remain the same?

Thanks,
Scott

**Comment by kevinvincent** [comment]
You can remove the configuration `device: "/dev/hidraw0"` from your config. Then the add-on will automatically find the right hidraw device and connect to it on each reboot.

**Comment by bronder** [comment]
> You can remove the configuration `device: "/dev/hidraw0"` from your config. Then the add-on will automatically find the right hidraw device and connect to it on each reboot.

Awesome!  Thanks for the help.
