### ISSUE TITLE
Errno 110 - Operation Time Out

### ISSUE THREAD

**Issue by phreaq** [kevinvincent/ha-wyzesense#165]
I am running Home Assistant 0.113.3, using I'm using 0.0.9 of the ha-wyzesense integration.

I have 6 different door sensors and one motion sensor that will all go offline 'at some point' in time. Once offline, none of the sensors update their status in HA. Rebooting HA will bring them back online, but I do need to open/close the sensors for their status to update accordingly. The sensors will work from anywhere from 1 to 5 days before going offline. The light on the Wyze Hub remains blue at all times.

I am running HA on a VirtualBox installed on Windows 10.

If I check the home assistant log, I see the following entries relating to 'wyze'

```
Search "wyze" (3 hits in 1 file)
  \\hassio\config\home-assistant.log (3 hits)
	Line 5: 2020-08-09 09:14:43 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
	Line 982: 2020-08-09 16:33:55 ERROR (Thread-2) [custom_components.wyzesense.wyzesense_custom] [Errno 110] Operation timed out
	Line 982: 2020-08-09 16:33:55 ERROR (Thread-2) [custom_components.wyzesense.wyzesense_custom] [Errno 110] Operation timed out
```
That time frame aligns with the time the sensors went offline.

Any thoughts?

**Comment by mattyb8562** [comment]
I had the same issue when using VB. There is at length discussion on #20 If I remember correctly it was an issue with VB and switching from USB eHCI to xHCI in VB fixed the issue.

**Comment by phreaq** [comment]
Thanks! I didn't see that thread earlier. Seems to describe my issue, I'll give it a try.
