### ISSUE TITLE
HomeKit Failing to Start - Likely Caused by Wyzeapi

### ISSUE THREAD

**Issue by IIAIronWolf** [kevinvincent/ha-wyzesense#171]
I keep getting an error message in my logs: `homeassistant.loader.IntegrationNotFound: Integration 'wyzeapi' not found.`

This seems to show up every time I try to manually start the HomeKit integration. I use the Wyze sensors for my security system so I do not want to remove this HACS integration if I don't have to. However, I cannot use HomeKit as of now. The homeassistant/core community could not find any other answer. I believe this integration is the issue because of the following log entry:
```
2020-09-01 18:17:38 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry HASS Bridge WGMO:51828 for homekit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 242, in async_setup_entry
    await homekit.async_start()
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 505, in async_start
    await self._async_set_device_info_attributes(
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 668, in _async_set_device_info_attributes
    integration = await async_get_integration(self.hass, ent_reg_ent.platform)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 454, in async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'wyzeapi' not found.
```

**Comment by IIAIronWolf** [comment]
Note: I do not currently, though I have in the past, have the HACS Wyzeapi integration installed.

**Comment by IIAIronWolf** [comment]
I have also opened an issue with Home Assistant for this: https://github.com/home-assistant/core/issues/39916#issue-698435017

**Comment by photinus** [comment]
What does your configuration for homekit look like? I dont use homekit, but I dont think we have any reference to "wyzeapi" in the module so it's likely unrelated

**Comment by photinus** [comment]
Looks to be related to https://github.com/Quantum-cross/ha-wyzeapi not this component.

**Comment by IIAIronWolf** [comment]
Why did you close this without getting more information first?? @photinus 
The link you sent me is a fork of the actual ha-wyzeapi for one; two, I only have ha-wyzesense installed, so how could it not have something to do with this?

**Comment by photinus** [comment]
Wyzeapi is a reference to the Wyze component for controlling the other wyze products. This repo is dedicated to the Wyze sense component only. I dont see anything in the error you posted here or in the issues you opened in the Home Assistant issue tracker that reference Wyze Sense

**Comment by IIAIronWolf** [comment]
That's exactly what's confusing me. I only have the ha-wyzesense component installed (via HACS) yet that message about wyzeapi appears in my logs. @photinus

**Comment by photinus** [comment]
Can you share your whole config (sanitized of any sensative data)?

**Comment by IIAIronWolf** [comment]
![image](https://user-images.githubusercontent.com/51146434/92803218-d1d34680-f37c-11ea-969f-bddb0b259193.png)
I thought I had figured it out. Checked the custom repositories in HACS and saw this guy still there ^

However, I just tried setting up HomeKit again and it did not work. Back to the drawing board. I will continue to work with the Home Assistant Core team and go to the wyzeapi guys if I have to.

**Comment by photinus** [comment]
If you can share your config, might be able to help troubleshoot.

**Comment by IIAIronWolf** [comment]
The only things I have in reference to wyze, in my configuration.yaml, are:
`binary_sensor:
  - platform: wyzesense
    device: auto`
and
`logger:
  default: warn
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug
    custom_components.wyzesense: debug
    wyzesense.gateway: debug`

**Comment by IIAIronWolf** [comment]
Fixed in: https://github.com/home-assistant/core/pull/39918
