### ISSUE TITLE
Services Unavailable V0.0.4

### ISSUE THREAD

**Issue by cjsteward** [kevinvincent/ha-wyzesense#18]
The services such as wyzesense.scan are unavailable after upgrading to V0.0.4. Downgrading to V0.0.3 resolved the issue. I'm running Hassio on an Intel NUC using HACS

**Comment by kevinvincent** [comment]
Any chance you could provide a log file (using the instructions at the bottom of the readme) of 0.0.4 running? I'd like to see what could be causing it.

**Comment by kevinvincent** [comment]
Closing due to lack of response and given that the question addresses an out of date version. If you are still running into issues please upgrade to v0.0.7 and re-open the ticket with a log if the problem persists.
