### ISSUE TITLE
Home Assistant 0.115.4 may have broken the wyzesense service for new installs

### ISSUE THREAD

**Issue by stizito** [kevinvincent/ha-wyzesense#181]
Hi. New here, but reasonably versed in all relevant open issues.

Rather than tag onto the two most relevant existing threads, whose titles and hypotheses may be missing the root cause, I've opted to create a new ticket with a summary of the symptom and links to relevant recent threads that may have the same root cause.

Specifically, when configuring a new Raspberry Pi 4 with a fresh install of Home Assistant 0.115.4, and installing wyzesense 0.0.9 through HACS, none of the wyzesense services appear to load. Older versions of wyzesense, specifically 0.0.8 and 0.0.7, have the same problem.

I believe this to be related to, if not the root cause of what [BullionMan](https://github.com/BullionMan) and [jsrich31](https://github.com/jsrich31) observe [here](https://github.com/kevinvincent/ha-wyzesense/issues/179#issuecomment-699025816), MikeTannenbaum notes [here](https://github.com/kevinvincent/ha-wyzesense/issues/150#issuecomment-668222282) (though his issue appears to have been resolved by reverting to wyzesense 0.0.8, which does not fix what I'm seeing) and [IIAlronWolf](https://github.com/IIAIronWolf) observed [here](https://github.com/kevinvincent/ha-wyzesense/issues/174#issuecomment-692818680) (though I strongly suspect the HomeKit idea was a red herring). Specifically, I suspect a conflict may be arising between recent HA builds, wyzesense, and - but this last one's a stretch - the latest Wyze bridge FW (0.0.0.33).

@kevinvincent - this may be worth a look. Happy to share logs if helpful.

@ all others, if my diagnosis appears to be missing something here, by all means, please let me know, as I expect this issue is likely affecting all others who are freshly installing wyzesense on HA 0.115.4.

My config:
Raspberry Pi 4 B
Docker version 19.03.11
host_os: HassOS 4.13
os_version: 4.19.127-v8
python_version: 3.8.5

Possibly relevant repositories:
HACS 1.6.0
wyzesense 0.0.9, 0.0.8, and 0.0.7 all appear to be affected by this issue

**Comment by jsrich31** [comment]
It would be great to see a fix that would resolve this issue. I also have tried all that is listed above to no avail. 

My config:
Raspberry Pi 4 B
docker version | 19.03.13
host os | Raspbian GNU/Linux 10 (buster)
installation type | Home Assistant Supervised
os name | Linux
os version | 5.4.51-v7l+
python version | 3.8.5
supervisor | 245
version | 0.115.6

**Comment by stizito** [comment]
Update:

Upon further investigation, and - frankly - trial and error, I've managed to get the services to load. Unclear which of the many steps I took resolved the issue, but here's an abbreviated list that is most likely to have addressed it:

1. Remove the wyzesense from HACS and associated config yaml sensor config
2. Restart device
3. # do lots of other stuff that's likely unrelated
4. Update to HA 0.115.6
5. Install wyzesense 0.0.8 through HACS
6. Restart device
7. Add appropriate text to config yaml (hard-coded to /dev/hidraw0, vs. auto)
8. Plug Wyze bridge directly into low-speed port
9. Restart, with Wyze bridge still plugged in

Far as I can tell/remember, besides the HA update, the fresh install of 0.0.8, and plugging in the Wyze bridge before the final config file change and restart are the likely reasons it's worked this time and didn't last.

Thanks and my apologies for the question/premise when additional troubleshooting resolved the issue. I'll close this thread and hope what's left here is helpful to others (@jsrich31 FYI).

**Comment by jsrich31** [comment]
Finally fixed this issue. There was a duplicate entry for binary_sensor: in my config file. I would run a test and everything was good and HA would work fine, but reviewing and cleaning up my files after seeing this is my logs did the trick. 

YAML file /config/configuration.yaml contains duplicate key "binary_sensor". Check lines 69 and 113

All is well.....😇
