### ISSUE TITLE
WyzeSense no longer working

### ISSUE THREAD

**Issue by SarcasticShrimp** [kevinvincent/ha-wyzesense#192]
A few days ago all my wyze sensors (motion and door) have stopped reporting changes.  I have rebooted both HA and the host several times without any luck.  Log here: https://pastebin.com/fbhpC0ra
Running Hassio in a Proxmox instance on a NUC.

my "System Health" info:
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.72
python_version | 3.8.6
supervisor | 2020.10.0
timezone | America/New_York
version | 0.117.1
virtualenv | false

binary_sensor:
  - platform: wyzesense
    device: auto

**Comment by roblefko** [comment]
Were you having issues prior to upgrading to .117?

**Comment by SarcasticShrimp** [comment]
no, it was right about the time I upgraded to .117 that it stopped working.

**Comment by roblefko** [comment]
Try rolling back to 0.116 to see if the problem is HA or the Wyze integration.

**Comment by fifa255** [comment]
See my comment in the link below. This may help fix the problem.

https://github.com/kevinvincent/ha-wyzesense/issues/189#issuecomment-719965534

**Comment by SarcasticShrimp** [comment]
Well I did another reboot yesterday evening, woke up this morning and noticed that all the sensors are working (except for one, but I think it might be damaged as it has not worked in weeks.)  I didn't change anything... I guess the 10th reboot is the charm???
