### ISSUE TITLE
NEW Wyze Sense Sensors???

### ISSUE THREAD

**Issue by war1000** [kevinvincent/ha-wyzesense#199]
anyone seen this? is it time to restart this project? :D
https://wyze.com/wyze-hms-bundle.html

**Comment by pickerin** [comment]
You'll have to do it yourself, as there's no one maintaining it any longer.
Also, this doesn't seem to address the issue of the sensors going offline when low on battery power and bricking.
Those of us who've invested in the sensors are moving off of them as a result (not interested in re-investing in all new sensors).
