### ISSUE TITLE
Motion sensor battery level reported as 102

### ISSUE THREAD

**Issue by SeanPM5** [kevinvincent/ha-wyzesense#2]
I've just updated to version `9ea846c` through HACS and tested the new persistent_notifications stuff which works great. Thanks for adding my feature request.

This was my first time scanning and adding the Wyze motion sensor and although it added and functions perfectly fine, it shows a battery_level of 102. Which would be awesome if true, but I'm pretty sure it's a bug 😛 

Not sure if there's anything else I can do to help beyond providing a screenshot. Not a big deal imo, just thought you should be aware of it.

![image](https://i.imgur.com/PPwiM6W.png)
![image](https://i.imgur.com/OultqGC.png)

**Comment by SeanPM5** [comment]
Also same thing for signal strength - it’s showing as 106 for one of my doors when the max should be 100. 

![image](https://i.imgur.com/Ql3Bsu5.png)

**Comment by kevinvincent** [comment]
Thanks for letting me know and for the screenshots! As I understand, the sensor reports battery level using just some basic calculations with the voltage. Maybe you just have an extra great battery, enjoy the slighly longer battery life :)

**Comment by kevinvincent** [comment]
Also I didn't realize you also mentioned signal strength. Signal strength is also just absolute value of the RSSI, not a percentage out of 100%. It's impossible to scale it to a percentage as theoretically the upper and lower bounds are not known. That value is also just passed straight from the hub to HA.

**Comment by SeanPM5** [comment]
I thought maybe this component was doing some minor miscalculation and that maybe it should be capped / rounded down to 100, but now that I know how it works I think it's better to just continue passing through the value untouched.

Thanks for clarifying, it's all good 😃
