### ISSUE TITLE
No 'version' key

### ISSUE THREAD

**Issue by PierreScerri** [kevinvincent/ha-wyzesense#203]
How do I fix this?

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 9:40:11 AM (2 occurrences)
Last logged: 9:40:19 AM

No 'version' key in the manifest file for custom integration 'wyzesense'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'wyzesense'

**Comment by bschatzow** [comment]
Since this card is not supported anymore I  edited the manifest file in notepad++ and added the same version line that one of my other cards that worked correctly was using. This worked an the error whent away.

**Comment by PierreScerri** [comment]
Yep.  That's exactly what I did after I posted.  All good now.
