### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by Krojack** [kevinvincent/ha-wyzesense#205]
I know this isn't maintained but maybe make a small update to support this so the Integration will keep working for us people using the devices still.

I'm getting the following warning in HA each time I restart.

> Logger: homeassistant.loader
> Source: loader.py:802
> First occurred: 2:31:53 PM
> Last logged: 2:31:53 PM
> 
> No 'version' key in the manifest file for custom integration 'wyzesense'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'wyzesense'
> 

If no update maybe let us know what file to edit and what to add to it so we can manually patch it?

**Comment by bschatzow** [comment]
You need to edit the manifest.json file with a text editor. 
Mine is:
```
{
    "domain": "wyzesense",
    "name": "Wyze Sense Component",
    "version": "1.8.2",
    "documentation": "https://github.com/kevinvincent/wyzesense",
    "requirements": ["wyzesense==0.0.4","retry==0.9.2"],
    "dependencies": [],
    "codeowners": ["@kevinvincent"]
}
```

**Comment by ballakers** [comment]
> You need to edit the manifest.json file with a text editor.
> Mine is:
> 
> ```
> {
>     "domain": "wyzesense",
>     "name": "Wyze Sense Component",
>     "version": "1.8.2",
>     "documentation": "https://github.com/kevinvincent/wyzesense",
>     "requirements": ["wyzesense==0.0.4","retry==0.9.2"],
>     "dependencies": [],
>     "codeowners": ["@kevinvincent"]
> }
> ```

Thanks for this, took me a bit to find the manifest under: /config/custom_components/wyzesense/manifest.json  for anyone else trying to find the manifest file.

**Comment by javellino** [comment]
>  /config/custom_components/wyzesense/manifest.json for anyone else trying to find the manifest file.

Thanks. this saved me some time.
