### ISSUE TITLE
NEW full-featured Python SDK for Wyze

### ISSUE THREAD

**Issue by shauntarves** [kevinvincent/ha-wyzesense#208]
I have recently released a full-featured, reverse-engineered Python SDK for Wyze devices. I would love to work with you to update/integrate your HA project.

If you don't plan on unmothballing this project, maybe you can link to my project from the front page so others can find it?

[Python SDK for Wyze](https://github.com/shauntarves/wyze-sdk)

**Comment by photinus** [comment]
This project never interacted with the Wyze API and was only focused on the local Wyze sense dongle.
