### ISSUE TITLE
Anyone seeing issue with WyzeSense after upgrading to 2021.6 or 2021.6.1?

### ISSUE THREAD

**Issue by wiiNinja** [kevinvincent/ha-wyzesense#213]
I upgraded to 2021.6/2021.6.1, and observe that HA no longer sees the door/motion Wyze sensors. I had to downgrade back to 2021.5.5. Has anyone successfully upgraded HA with functional WyzeSense? I did not see any breaking change in the HA release note related to Wyze.

**Comment by photinus** [comment]
What version of the WyzeSense component are you using?

**Comment by wiiNinja** [comment]
I am using v0.0.11

**Comment by wiiNinja** [comment]
I wanted to turn on logging but didn't know the tag for it.

**Comment by wiiNinja** [comment]
On a 3rd upgrade from 2021.5.5 to 2021.6.1, with logger turned ON (custom_components.wyzesense), it works. :)
