### ISSUE TITLE
HASS 2021.12: WyzeSensor implements device_state_attributes

### ISSUE THREAD

**Issue by IvanUA** [kevinvincent/ha-wyzesense#219]
From the HASS 2021.12 log:
_<class 'custom_components.wyzesense.binary_sensor.WyzeSensor'>) implements device_state_attributes. Please report it to the custom component author._
Please advise how to fix

**Comment by worldgod13** [comment]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 8:04:37 AM (6 occurrences)
Last logged: 8:04:38 AM

Entity binary_sensor.kitchen_motion_sensor (<class 'custom_components.wyzesense.binary_sensor.WyzeSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.basement_motion_sensor (<class 'custom_components.wyzesense.binary_sensor.WyzeSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.stairway_motion_sensor (<class 'custom_components.wyzesense.binary_sensor.WyzeSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.basement_door (<class 'custom_components.wyzesense.binary_sensor.WyzeSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity binary_sensor.garage_side_door (<class 'custom_components.wyzesense.binary_sensor.WyzeSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by worldgod13** [comment]
> From the HASS 2021.12 log: _<class 'custom_components.wyzesense.binary_sensor.WyzeSensor'>) implements device_state_attributes. Please report it to the custom component author._ Please advise how to fix

I fixed mine I believe. Edit /config/custom_components/wyzesense/binary_sensor.py line 241 changed from def device_state_attributes(self): to def extra_state_attributes(self):

After reboot I had no warnings.

**Comment by IvanUA** [comment]
Thank you @worldgod13. That solved the issue. Also I see that there's a PR for that already.
