### ISSUE TITLE
Wyze light bulb support?

### ISSUE THREAD

**Issue by saicrazyfire** [kevinvincent/ha-wyzesense#22]
This component worked flawlessly for my motion sensor. Is there anyway to support the recently shipped light bulbs (https://www.wyze.com/wyze-bulb/)?

**Comment by zackoch** [comment]
@saicrazyfire they use totally different protocols.

I've been trying to hack the bulb for a little over a week now. It appears the bulb is being managed by MQTT, but it's encrypted ... I dumped the firmware from a bulb but I'm having a hard time trying to split the firmware into its proper segments. (The flash is separated into loader, and two ota images) I need to get to the code so I can see how it's registering with the API - I suspect the API tells the bulb which MQTT channel to subscribe to or something. Dunno.

**Comment by zackoch** [comment]
Well - I finally got a a clean copy of the firmware....

I've tried to load it into ida and radar but I'm way over my head at this point.

Hopefully this is useful for someone!

[fw.zip](https://github.com/kevinvincent/ha-wyzesense/files/3845477/fw.zip)

**Comment by photinus** [comment]
I feel like this is out of scope for this project. Good info, but it's a different product and a whole different area of expertise needed.

It is based on the ESP8266 family, if there is some way to trick it into loading a custom firmware, I'm guessing it could be made to work rather easily with Tasmota or ESPHome
