### ISSUE TITLE
Core 2022.4.0 looses sensor attributes

### ISSUE THREAD

**Issue by sweichbr** [kevinvincent/ha-wyzesense#223]
I know this project is technically dead, but I just updated my HA to 4.0 and all wyze sense attributes are gone (and we all know how important the battery level is).

Anyone know what the issue may be?

**Comment by sweichbr** [comment]
Falling back to 3.8 and the sensors are back.

**Comment by stanwebber** [comment]
i can confirm this behavior. i'll wait to see if anything changes in 2022.4.1, but if not i'll be rolling back to 2022.3.8 and staying there maybe indefinitely.

**Comment by bschatzow** [comment]
Same for me. I did not notice it on the beta ( I wish I had seen it there and reported it).

**Comment by strikeir13** [comment]
This is because of the change from `device_state_attributes` to `extra_state_attributes`. There is an open pull request to resolve this, but the change in the pull request can also be manually added to address the error: https://github.com/kevinvincent/ha-wyzesense/pull/218

**Comment by stanwebber** [comment]
i have the fix in #218 applied, but the sensor attributes are still lost in 2022.4.0.

**Comment by bschatzow** [comment]
I manually changed my file and the attributes are back.

**Comment by sweichbr** [comment]
Yup. Worked for me too. Thanks @strikeir13 for the tip.

**Comment by stanwebber** [comment]
well hell. thought i had merged a pull request with this fix in my fork back in jan, but i must have forgotten about it. merged the fix and updated my custom components, but the attributes are still missing. not sure what to look at next.

**Comment by sweichbr** [comment]
I just went into the wyzesense/binary_sensor.py and made the change. Then
restarted HA and they reappeared.

**Comment by bastero** [comment]
> I manually changed my file and the attributes are back.

Forgive my ignorance...Can you be more specific about the change in 'custom_components/wyzesense/binary_sensor.py' ? 

What I understand is to change the function's name i.e. 'device_state_attributes' to 'extra_state_attributes'. save and reboot HA. If there is any other change(s) required please advise.

However, this change below doesn't show the attributes once I reboot HA. Please clarify, thank you.

```
   def extra_state_attributes(self):
        """Attributes."""
        attributes = self._data.copy()
        del attributes[ATTR_STATE]
        del attributes[ATTR_AVAILABLE]
```

**Comment by bschatzow** [comment]
The only change I made to my binary_sensor.py file was
```
    @property
    def extra_state_attributes(self):
```
Make sure that you used a text editor and did not change any of the spaces.
Mine worked as soon as I did a restart or HA

**Comment by Kev7274** [comment]
> > I manually changed my file and the attributes are back.
> 
> Forgive my ignorance...Can you be more specific about the change in 'custom_components/wyzesense/binary_sensor.py' ?
> 
> What I understand is to change the function's name i.e. 'device_state_attributes' to 'extra_state_attributes'. save and reboot HA. If there is any other change(s) required please advise.
> 
> However, this change below doesn't show the attributes once I reboot HA. Please clarify, thank you.
> 
> ```
>    def extra_state_attributes(self):
>         """Attributes."""
>         attributes = self._data.copy()
>         del attributes[ATTR_STATE]
>         del attributes[ATTR_AVAILABLE]
> ```

Same here,doesn't work.

**Comment by bastero** [comment]
> The only change I made to my binary_sensor.py file was
> 
> ```
>     @property
>     def extra_state_attributes(self):
> ```
> 
> Make sure that you used a text editor and did not change any of the spaces. Mine worked as soon as I did a restart or HA

I used VSCode to edit and the spaces are correct. I'll reboot the whole system just in case something else is interfering..

**Comment by stanwebber** [comment]
it's been 2 days and i've restarted the host and hass a couple times, but i'm not seeing any attributes. i even pulled the custom components folder via sftp to manually verify the binary_sensor.py file had the fix and it did.

**Comment by Kev7274** [comment]
Everything seems to be working again. I had to retrigger the sensors for them to show up.

**Comment by stanwebber** [comment]
working now--all devices need to be physically triggered after the change. i lost a contact sensor (dead even with fresh battery) which added to the confusion.
