### ISSUE TITLE
Wyze Sense Battery reporting non-numeric values (on:off) instead of a battery percentage.

### ISSUE THREAD

**Issue by stang70man** [kevinvincent/ha-wyzesense#224]
After one of the recent updates to Home Assistant, the Wyze V1 sensors are no longer reporting a battery percentage, but instead are reporting an on:off state.

**Comment by stanwebber** [comment]
what version did you notice this? i'm on 2022.4.7 and can report no issue. i briefly updated to 2022.5.4, but had to roll back because db_url: 'sqlite:///:memory' is no longer a valid recorder configuration option.

**Comment by bschatzow** [comment]
I am on the latest version of HA and have no issues.  There was a change required to the json file several months ago. Look in the released code and you should be able to find what needs to be changed. If you can't find it, let me know and I'll get a link to it when I get home

**Comment by stang70man** [comment]
> what version did you notice this? i'm on 2022.4.7 and can report no issue. i briefly updated to 2022.5.4, but had to roll back because db_url: 'sqlite:///:memory' is no longer a valid recorder configuration option.

I believe it started when I went to 2022.4.

**Comment by stang70man** [comment]
> I am on the latest version of HA and have no issues. There was a change required to the json file several months ago. Look in the released code and you should be able to find what needs to be changed. If you can't find it, let me know and I'll get a link to it when I get home

I checked my manifest.json and it matches the version in source for the newest version. I've searched around and have not been able to find anything about a change that needed to be done. If you could share what you know, I'd really appreciate it.

**Comment by bschatzow** [comment]
device_state_attributes' is deprecated starting with HA 2021.12.0
replaced 'device_state_attributes' with 'extra_state_attributes'

**Comment by stanwebber** [comment]
ha-wyzesense master is out of date. use someone elses fork with all the current updates. try mine if you like...whichever you choose consider forking that yourself.

**Comment by stang70man** [comment]
That did it for me after resetting the sensors. Thanks everyone!
