### ISSUE TITLE
Ready for Python 3.10?

### ISSUE THREAD

**Issue by Joeviocoe** [kevinvincent/ha-wyzesense#226]
Am I the only one still running v1 WyzeSense sensors?
I got a TI LaunchPad CC1310 just to keep these sensors going (unbricking).

Anyway, Home Assistant has upgraded to Python 3.10, and before I update, I want to make sure it won't break the ha_wyzesense component.  Any way to test just the component without upgrading HA?

**Comment by bschatzow** [comment]
I still have version 1 hub and both version 1 and 2 sensors. No issues for me with the update.

**Comment by bschatzow** [comment]
I am on HAOS 2022.7.1, OS 8.3. This includes the latest python version which was tested during the beta release

**Comment by sweichbr** [comment]
Just curious. Don't know if it's related to the update but all my wyze sensors no longer report battery level and the bridge led is off

**Comment by bschatzow** [comment]
Try a shutdown and restart. If bridge is off it isn't working.

**Comment by sweichbr** [comment]
Have tried that.  Plus the sensors themselves are still triggering, just the attributes that are missing.

**Comment by bschatzow** [comment]
The attribute issue is a different issue.  You need to fix ( I believe the py file).   Go to the wyzesense GitHub site and you will find directions there.

**Comment by sweichbr** [comment]
Thanks so much. That fixed it.

Sorry for hijacking the thread.

**Comment by ctrl50** [comment]
I run ha in a venv on ubuntu 22.04 and have had python 3.10.4 running for months no issues.

**Comment by Joeviocoe** [comment]
Thank you.  I've upgraded and it works.

**Comment by sweichbr** [comment]
Have tried that.  Plus the sensors themselves are still triggering, just
the attributes that are missing.

**Comment by stanwebber** [comment]
i run on my own fork with v1 door and motion sensors. i was stuck on core-2022.4.7 for a long time, but recently upgraded to core-2022.10.3 on hassos 9.2. other than needing to recover the mac on 1 of my door sensors (currently working with 00000000 mac), i can report no other issues.
