### ISSUE TITLE
WyzeSense changes USB Port Assignment in HA running on VMWare

### ISSUE THREAD

**Issue by cknieriem** [kevinvincent/ha-wyzesense#24]
Just wanted to mention that my HA installation changes USB port.  I am running HA on VMWare and running a stock installation of HASSOS.  Ports change as follows:
device: "/dev/hidraw0"
to
device: "/dev/hidraw1"

Have had this happen very rarely but if your Wyze Sense stops working check this setting.

**Comment by samgangiah** [comment]
I've had similar behavior on a RPi3B. It changed between restarts of HA

**Comment by bigbry87** [comment]
Having the same problem. Changes from "/dev/hidraw0" to "...1" after each reboot.
My setup:
Hassio
VirtualBox 6.0
Windows 10 64bit 

*just for the time being, I have put it back in the Camera and using "IFTTT".

**Comment by w1tw0lf** [comment]
Having a similar issue with Virtualbox on ubuntu.

Seems like it is a power issues on the USB port with the host switching the port to sleep. Try an disable power management on the host USB ports. Seems to have solved it for me.

**Comment by kevinvincent** [comment]
Hi all, there's a new update that addresses this issue. Please update and set device to "auto".
