### ISSUE TITLE
Must Disable WyzeSense to Update Hassio

### ISSUE THREAD

**Issue by tggman** [kevinvincent/ha-wyzesense#25]
Everytime I try to update my Hassio installation the update fails and the Hassio front end fails to load. However, the SSH server and Samba share are up and running as expected during the event. WyzeSense is my only custom_component.  

Workaround:
The only way I've been able to successfully install any Hassio update is to (1) disable WyzeSense by renaming the custom_component folder to custom_component.disabled (or whatever), (2) perform the update, (3) rename custom_component folder back, and (4) restart. After that, all is well including any subsequent restarts.

I'm running Hassio is v0.98.2  on a Raspberry Pi 3B+. The SSH server, Samba Share and DuckDNS service with Let's Encrypt add-ons are installed.

[Hassio Fail to Restart.log](https://github.com/kevinvincent/ha-wyzesense/files/3579871/Hassio.Fail.to.Restart.log)

**Comment by photinus** [comment]
I'm running Hassio and have not seen the issue. I dont see anything in the log that would give me any reason to think that WyzeSense is causing it, but cant really say one way or another.

**Comment by tggman** [comment]
This custom integration is no longer supported by the author.

Note: The Fail to Start issue eventually self-corrected itself for no apparent reason.
