### ISSUE TITLE
Triggers 

### ISSUE THREAD

**Issue by bschatzow** [kevinvincent/ha-wyzesense#27]
Can you add to the documentation what the triggers are.  Off / on, open /closed, clear / detected?  
I was not getting my automation to trigger and I believe I have used the wrong triggers.

**Comment by daphatty** [comment]
This information already exists in the documentation. Look at the "Notes on Individual Sensors" category under the Usage section.

https://github.com/kevinvincent/ha-wyzesense#usage

**Comment by kevinvincent** [comment]
As @daphatty mentioned above: "on" and "off" are the states it uses and the meanings are located at the link.
