### ISSUE TITLE
Is the timestamp attribute being set properly?

### ISSUE THREAD

**Issue by genem2** [kevinvincent/ha-wyzesense#3]
This component is working great! Thank you for your work on this.
I am noticing however, that these sensors appear to be one-hour off on the timestamp attribute.

Wondering if that could be me, in some way.  The Pi's time is set properly:

![2019-08-07_20-37-12](https://user-images.githubusercontent.com/46231389/62673459-5d48ff80-b953-11e9-9f4b-c70db20122fc.png)

**Comment by kevinvincent** [comment]
You're right, It's passing the timestamp through from what it gets from the hub... but the hub might be reporting it incorrectly. I'll check mine too and if it's off I'll change it to use the local instance's time. You can expect that change later tonight :)

**Comment by kevinvincent** [comment]
Actually, on second thought... I think it might be an issue with your configuration. Can you add this time_date sensor platform to your home assistant config: https://www.home-assistant.io/components/time_date/
and let me know if that matches the sensor timestamp or your pi's time stamp?

**Comment by genem2** [comment]
The time_date sensor was reporting things find, but it appears the timedatectl setting was the culprit. Strange that this is the first time I'm affected by this.

I'm sorry to have bothered you with this.

**Comment by kevinvincent** [comment]
No worries at all! Your issue made me wonder what the timezone setting on my host was and turns out mine was off too. Thanks!
