### ISSUE TITLE
Contact Sensor device class (door/window)

### ISSUE THREAD

**Issue by 4841penoyer** [kevinvincent/ha-wyzesense#41]
I have a good number of contact sensors that I'm using to monitor the status of windows, but they all use a door for their icon.  I went into Home Assistant and changed the device class from Door to Window and they started to show up as windows.  

However, whenever the windows are opened or closed the device type reverts to door.  

Looks like it is these two lines of code (I don't really know Python)  

Sets the device type to door (or motion)
https://github.com/kevinvincent/ha-wyzesense/blob/e826fd88ae0ccd819e694e577d53a46ae543d05f/custom_components/wyzesense/binary_sensor.py#L62

Overwrites all data
https://github.com/kevinvincent/ha-wyzesense/blob/e826fd88ae0ccd819e694e577d53a46ae543d05f/custom_components/wyzesense/binary_sensor.py#L75

Is it possible change this behavior so it doesn't update the device class whenever a state change is triggered?

**Comment by mikeyroth** [comment]
I am also a "new to python" hobbyist.   I understand the need to do device class on first run, but after that, does it need to do it when it updates?

**Comment by 4841penoyer** [comment]
Yup root cause was me doing it wrong.  I was editing values in the wrong location so they weren't designed to survive an update.  

Anyone else seeing this follow this documentation on how to enable to customize tab and make the changes there.  
https://www.home-assistant.io/docs/configuration/customizing-devices/
