### ISSUE TITLE
[Feature Request] Wyze Plug support

### ISSUE THREAD

**Issue by scadaguru** [kevinvincent/ha-wyzesense#48]
I am not this can fall under the scope of this project but it will be nice to have support for Wyze Plug. 
Here is the product details from Wyze and they say use WyzeSense to control/automate the plugs.
https://wyze.com/wyze-plug.html
Thanks and appreciate good work!

**Comment by kevinvincent** [comment]
Yeah, unfortunately, this is out of scope as the communication is over wifi instead of through the dongle.
