### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by BenRoc1979** [kevinvincent/ha-wyzesense#50]
Hi!

Here's my setup:
unraid server, home assistant docker.
/dev/hidraw0 is passed to the HA docker. I see it in the HA docker console.
I installed thru HACS, added the lines to my configuration.yaml
The sensor light stays orange, and I get  the following message:

`Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 82, in setup_platform
    ws = beginConn()
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-2>", line 2, in beginConn
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/config/custom_components/wyzesense/binary_sensor.py", line 80, in beginConn
    return Open(config[CONF_DEVICE], on_event)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 561, in Open
    return Dongle(device, event_handler)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 297, in __init__
    self._Start()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 492, in _Start
    self._Inquiry()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 398, in _Inquiry
    resp = self._DoSimpleCommand(Packet.Inquiry())
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 393, in _DoSimpleCommand
    self._DoCommand(pkt, cmd_handler, timeout)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 379, in _DoCommand
    self._SendPacket(pkt)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 331, in _SendPacket
    pkt.Send(self.__fd)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 106, in Send
    ss = os.write(fd, pkt)
BrokenPipeError: [Errno 32] Broken pipe`

I tried reinstalling thru HACS, rebooted multiple time, no luck. 

Any clues?

**Comment by NPGHome** [comment]
Hi, 
Thank you for that. I have the same issue as above. It happened yesterday as well. I cannot move any further than the amber light. Reinstalled, copied files through hassio configurator, through SSH etc. Please help. My log below.

_

> 2019-10-28 21:09:34 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
> 2019-10-28 21:09:35 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
> 2019-10-28 21:10:04 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform wyzesense
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
>     await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
>   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
>     return fut.result()
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/wyzesense/binary_sensor.py", line 82, in setup_platform
>     ws = beginConn()
>   File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-2>", line 2, in beginConn
>   File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
>     logger)
>   File "/usr/local/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
>     return f()
>   File "/config/custom_components/wyzesense/binary_sensor.py", line 80, in beginConn
>     return Open(config[CONF_DEVICE], on_event)
>   File "/config/custom_components/wyzesense/wyzesense_custom.py", line 561, in Open
>     return Dongle(device, event_handler)
>   File "/config/custom_components/wyzesense/wyzesense_custom.py", line 297, in __init__
>     self._Start()
>   File "/config/custom_components/wyzesense/wyzesense_custom.py", line 492, in _Start
>     self._Inquiry()
>   File "/config/custom_components/wyzesense/wyzesense_custom.py", line 398, in _Inquiry
>     resp = self._DoSimpleCommand(Packet.Inquiry())
>   File "/config/custom_components/wyzesense/wyzesense_custom.py", line 393, in _DoSimpleCommand
>     self._DoCommand(pkt, cmd_handler, timeout)
>   File "/config/custom_components/wyzesense/wyzesense_custom.py", line 379, in _DoCommand
>     self._SendPacket(pkt)
>   File "/config/custom_components/wyzesense/wyzesense_custom.py", line 331, in _SendPacket
>     pkt.Send(self.__fd)
>   File "/config/custom_components/wyzesense/wyzesense_custom.py", line 106, in Send
>     ss = os.write(fd, pkt)
> BrokenPipeError: [Errno 32] Broken pipe
> 2019-10-28 21:10:05 WARNING (MainThread) [homeassistant.setup] Setup of asuswrt is taking over 10 seconds.

_

**Comment by BenRoc1979** [comment]
Here's my pastebin: https://pastebin.com/LXaHJs59

**Comment by zachishi** [comment]
Same broken pipe error. https://pastebin.com/5z8GELfm

I am running a VM on a unraid server. Hassio. Worked previously but after update to 101.2 i have been having issues.

**Comment by BenRoc1979** [comment]
Mine finally works. 
Changed USB port and also updated my bios to the latest version, and not it's detected properly. Try that out, it's 'setup' related, not the actual hassio code.

**Comment by zachishi** [comment]
Got mine working by using the Auto rather than /dev/hidraw1 and a different binary_sensor.py https://github.com/kevinvincent/ha-wyzesense/blob/cb84cf822d49cee9fc3cb1386bb43e66bb28f17b/custom_components/wyzesense/binary_sensor.py

**Comment by teankum** [comment]
> Got mine working by using the Auto rather than /dev/hidraw1 and a different binary_sensor.py https://github.com/kevinvincent/ha-wyzesense/blob/cb84cf822d49cee9fc3cb1386bb43e66bb28f17b/custom_components/wyzesense/binary_sensor.py

how did you do this? did you put this in the configuration.yaml

**Comment by genem2** [comment]
> Got mine working by using the Auto rather than /dev/hidraw1 and a different binary_sensor.py https://github.com/kevinvincent/ha-wyzesense/blob/cb84cf822d49cee9fc3cb1386bb43e66bb28f17b/custom_components/wyzesense/binary_sensor.py

**_THANK YOU!_**
Moving from a Pi to Docker in unRAID today and this was a multi-hour pain.
I replaced the std binary_sensor.py with the one you're linking here, exposed /dev/hidraw0 to the docker and I'm up.
