### ISSUE TITLE
[Errno 71] Protocol error

### ISSUE THREAD

**Issue by aaronpk** [kevinvincent/ha-wyzesense#53]
About 3 hours after rebooting Home Assistant, I see this in the logs:

```
2019-10-27 04:43:03 ERROR (Thread-2) [custom_components.wyzesense.wyzesense_custom] [Errno 71] Protocol error
```

Nothing else before that and nothing after it. The sensors stop reporting after that.

**Comment by kevinvincent** [comment]
Hi @aaronpk. That occurs when theres an issue reading and writing to the usb device. Has it occurred more frequently?

**Comment by aaronpk** [comment]
It was happening pretty often on the Raspberry Pi, but I switched to an Intel NUC and haven't had any issues with the library at all since then! I guess there's just something wrong with the Pi.

**Comment by kevinvincent** [comment]
Yeah... unfortunately the Pi has a bunch of issues with this library. Most people on other platforms like the NUC or just other PCs have 100% stability. I personally run it off a microsoft surface and its been rock solid for months now.
