### ISSUE TITLE
Home Assistant does not start if device not found

### ISSUE THREAD

**Issue by mrmin24** [kevinvincent/ha-wyzesense#54]
Hi,

I have an issue where if the Wyze device is not found in the hidraw(x) where it is configured or if the device is not plugged in, then Home Assistant runs the CPU up to 100% use and never actually starts up. Is there a way to prevent this.

Also, is there a way to prevent the hidraw(x) number changing in ubuntu. It changes everytime on reboot.

Thx

**Comment by blaster452** [comment]
I am also having this problem. I like this setup but an unable to use it due to the changing hidraw number on reboot. I am using docker on a NUC running ubuntu. If there was a way to force the same number on reboot I think this issue would stop.

**Comment by mrmin24** [comment]
there is a possible fix which I have not yet been able to test properly. It is currently in the pull-requests where the Wyze is automatically detected. 
[https://github.com/kevinvincent/ha-wyzesense/pull/44](https://github.com/kevinvincent/ha-wyzesense/pull/44)

Wyze is seemingly somewhat unstable at boot and I am not 100% sure what is causing it. Will test some more and provide feedback.

**Comment by blaster452** [comment]
Just an update - I updated the file as in the pull request and my problem seems to be fixed. Have only done a couple of reboots and seems fine. I could not complete any reboots before the change.

**Comment by mrmin24** [comment]
Thx for the update. Can you please monitor and provide some feedback on the stability. 
For some reason my HASSIO is unstable in that some services stop working, could be that the server is running out of resources. I think it is still caused by Wyze. I am currently running it without Wyze to see if the problem re-occurs.

**Comment by blaster452** [comment]
Second update - now about 8 to 10 restarts of home assistant with zero problems. Wyze rock solid since changes.

**Comment by krystoffuk** [comment]
I’ve been having this issue too and was preventing me using the integration, have to manually comment out the lines in the configuration file and then reboot to get home assistant running in this situation, glad it wasn’t just me, hope your testing goes well

**Comment by kevinvincent** [comment]
Hi all. There's a new release that adds automatically detecting the wyzesense device that should fix this issue. Please update through HACS.

**Comment by krystoffuk** [comment]
Hey Kevin
Got your notification last night and updated.
Can report 100% success
My wyzesense entry in the configuration file now doesn’t hang Hassio & putting the auto option in picked up my sensor hub plugged in after that and bought through my motion and door sensors!
Thanks so much!!
Krys

Kind Regards

Chris
________________________________

**Comment by mrmin24** [comment]
This is great, thank you. 

I am still testing stability as mine seems to fall over after 24 hrs or so, but it might be PC problem - something to do with HIDRAW. 

Thx

**Comment by kevinvincent** [comment]
Hi @mrmin24 
Yeah... unfortunately there's a lot of weird edge cases with hidraw devices. I've noticed that pi's especially seem to have more issues. I know of people running this on NUCs and other devices (my personally on a microsoft surface) with months of 100% reliability. I hope this helps with the stability.

**Comment by kevinvincent** [comment]
Hi @mrmin24 is it still looking good? Any issues?

**Comment by mrmin24** [comment]
> Hi @mrmin24 is it still looking good? Any issues?

Hi @kevinvincent, yes thank you. I believe the system has been running the whole week without any issues. Thanks a lot
