### ISSUE TITLE
Sudden _doCommand Error 

### ISSUE THREAD

**Issue by thychubbz** [kevinvincent/ha-wyzesense#55]
Hassio 0.101.3 on Pi 3
Log: https://pastebin.com/raw/m9mR6c7P

I just noticed today that when I restarted Home Assistant, the majority of my Wyze sensors were not available. I haven't changed anything from my configuration, so I am unsure how to proceed. 

I interpreted the message below from Troubleshooting as reinstalling the component, but when I went to reinstall from HACS, nothing changed.

"Ensure that you have updated to the latest component code. If you still see this error follow Reporting an Issue below."

Any help is greatly appreciated :)

**Comment by thychubbz** [comment]
To add some detail to this, I have already tried the following:

- Downgrading to Hassio 0.100.0, 0.99.0
- Uninstalling "Wyze Sense Component" from HACS, and reinstalling it
- Installing v0.0.4, issue still persists

I have also removed the USB extension cable that I was using to position the sensor better, however the issue is persistent. I am unsure what I have missed.

**Comment by tripp396** [comment]
Same issue here for me

**Comment by tripp396** [comment]
Hmmm interesting, just tried unplugging the hub, plugging it back in and restarting home assistant and that cleared the error and I have my sensors back

**Comment by thychubbz** [comment]
Dear future readers,

My solution was to apply [this package](https://github.com/photinus/ha-wyzesense) instead of the one from this repo. Allowed me to use the WyzeSense services to remove everything from the antenna and then repair them.

Process was painful, but I'm glad I got that sorted.

**Comment by thychubbz** [comment]
Dear future readers,

My solution was to apply [this package](https://github.com/photinus/ha-wyzesense) instead of the one from this repo. Allowed me to use the WyzeSense services to remove everything from the antenna and then repair them.

Process was painful, but I'm glad I got that sorted.
