### ISSUE TITLE
Wyze Sense USB-adapter yields no /dev/hidraw* on Mac OS with Dockerized Home Assistant 

### ISSUE THREAD

**Issue by mikaeledstrom** [kevinvincent/ha-wyzesense#56]
When I connect the Wyze Sense USB-adapter into my Mac (tried both Macbook Pro and Mac mini), I see no /dev/hidraw device in terminal with ls command. I have done a quick comparison of the direcory listing and I see this as new: /dev/ttys00*. 

I have shared /dev/ttys00* with Dockerized Home Assistant and updated the configuration.yaml but without any luck. 

Has anybody got the Wyze sense USB-adapter to work with Mac as host? It seems like hidraw is not supported in Mac OS. I have installed hidapi through brew but no improvement.

**Comment by photinus** [comment]
I dont believe Mac OS supports HIDRAW which would prevent the add-on from working.

**Comment by kevinvincent** [comment]
Hi @mikaeledstrom as @photinus mentioned Mac OSX, unfortunately, does not support hidraw devices. I have added this warning to the wiki.
