### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by teankum** [kevinvincent/ha-wyzesense#61]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 57, in setup_platform
    _LOGGER.debug("Attempting to open connection to hub at " + config[CONF_DEVICE])
TypeError: can only concatenate str (not "NoneType") to str

**Comment by teankum** [comment]
I'm using this binary file
https://github.com/kevinvincent/ha-wyzesense/blob/master/custom_components/wyzesense/binary_sensor.py

**Comment by Nighteyez07** [comment]
I've been getting this same issue
Hassio on top of Ubuntu
Installed this via the latest version of HACS. I'll pull specific versions of everything when I get back home.

**Comment by teankum** [comment]
That's the setup I have as well. Hopefully it can get resolved soon.

**Comment by Nighteyez07** [comment]
@teankum I got it working, with the following steps

1. Implemented the code changes from this pending PR https://github.com/kevinvincent/ha-wyzesense/pull/44
1. Remove the _device: ""_ for the wyzesense platform under binary sensor in your configuration.yml
1. Unplug and plug back in the Wyze Bridge
1. Restart Home Assistant and check the logs

**Comment by Nighteyez07** [comment]
This issue was causing my HA instance to basically not work at all, once I got it resolved my HA is now super responsive once again.

**Comment by teankum** [comment]
@Nighteyez07  Did you put the following in your configuration file?

- platform: wyzesense
  device: auto

I already had that in my code. Also, are you using the standard binary file or are you using 

https://github.com/kevinvincent/ha-wyzesense/blob/master/custom_components/wyzesense/binary_sensor.py

**Comment by Nighteyez07** [comment]
I was using the standard binary installed directly from HACS, but I manually edited the binary_sensor.py with the edits in the PR. Then edited my configuration to completely remove the _device: auto_ line from the wyzesense platform.
`- platform: wyzsense`

**Comment by teankum** [comment]
@Nighteyez07  I changed the configuration file to 
binary_sensor:
  - platform: wyzesense

I am still getting the error.  Is your binary file the same as this?

https://github.com/kevinvincent/ha-wyzesense/blob/cb84cf822d49cee9fc3cb1386bb43e66bb28f17b/custom_components/wyzesense/binary_sensor.py

**Comment by teankum** [comment]
@kevinvincent Do you have a fix for this?

**Comment by kevinvincent** [comment]
Yes, please update via HACS and remove the device field from your config

**Comment by dnaphreak** [comment]
Had this same issue using Hassio on top of Debian after updating to version 0.0.6 via HACS.
These are the steps that got it working again.
1. Set device: "auto" in config
2. Unplug and replug Wyze Bridge
3. Restart HA instance

**Comment by jchuck5612** [comment]
Using version 0.0.6 - I fixed this issue by moving the Wyze bridge from the camera to my Raspberry Pi.

**Comment by kevinvincent** [comment]
Closing as this has been fixed in 0.0.6
