### ISSUE TITLE
I'm having issues pairing wyze door sensors

### ISSUE THREAD

**Issue by cditt** [kevinvincent/ha-wyzesense#68]
I'm having issues pairing wyze door sensors with the wyze receiver. I followed digblurDIY video and Kevin  Vincent github page but no luck. Configuration.yaml
binary_senor:
    -  platform: wyzesense
       device: "/dev/hidraw0"
The receiver is solid blue. When I hit the scan in services it blinks blue and I put the pin in the door sensor and it blinks red three time and nothing happens. Home assistant notification says no sensors found. I've also tried 
binary_senor:
    -  platform: wyzesense
       device: auto
But I'm not having any luck. I need help and I'm new to this less then 6 months no experience. Learn as I go

**Comment by onebyside** [comment]
binary_sensor:
  - platform: wyzesense
    device: "/dev/hidraw0"

**Comment by teslawave** [comment]
are you doing a restart before trying to add your sensors?

**Comment by cditt** [comment]
yes..... still getting 

wyzesense
Scan completed with no sensor found.

**Comment by typhoonss92** [comment]
I am having the same issue. RPi4 HassOS. the hub shows, press wysesense.scan service call, blue light on hub blinks put pin in sensor see the red led 3 times, I have tried right next to the hub. after 30 seconds get notification in HA no sensor added. I enabled the logger and here is my https://pastebin.com/MJPVmG4b
not sure this tells much from what I have looked thru.
I have tried unplugging and using another port, I am using the usb 2.0 port. 
I am on the newest everything, 103.6ha, HassOS 3.8, Hassio supervisor 195

**Comment by typhoonss92** [comment]
I wanted to update that I finally got the sensors to add. Not sure exactly what made them update but here are the tings I did. on the hub there is a button I held that for 8-10 seconds, Per Wyze this should reset the hub and release all sensors(which I never had connected), next I deleted the __pycache__ folder in the wyzesense folder under custom components. Took the batterys out of the sensors for a few minutes. Put the batterys back in and rebooted the RPi. Once back up the sensors added. Again not sure what did it but they are working now.

**Comment by cditt** [comment]
It worked. Outstanding. Thanks for the update.

**Comment by kevinvincent** [comment]
Weird. I'm glad you were able to find a solution. Please make sure that you're running the latest component version as well (v0.0.7). There seems to be some issue when the hub reports a sensor mac address as 000000 which totally breaks things but is fixed by a hub reset. The new update will at least allow me to figure out if that is the problem if this occurs again. Going to close this issue out for now, please re-open if it re-occurs.
