### ISSUE TITLE
Error in my configuration file

### ISSUE THREAD

**Issue by Erdcgh** [kevinvincent/ha-wyzesense#69]
When I just add the following to my configuration.yaml per the instructions, I receive an error an of "parsing a block mapping"

- platform: wyzesense
  device: auto

Should it not have one line before these two lines? Something like:
wyzesense:

**Comment by teslawave** [comment]
this is a binary sensor it should be under 
binary_sensor:
  - platform: wyzesense
    device: "/dev/hidraw0"

**Comment by Erdcgh** [comment]
Great Thanks! But now that I have done that I get this in my error log:

`Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 149, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 94, in setup_platform
    result = ws.List()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 507, in List
    sensors = self._GetSensors()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 479, in _GetSensors
    self._DoCommand(Packet.GetSensorList(count), cmd_handler, timeout=self._CMD_TIMEOUT * count)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 384, in _DoCommand
    raise TimeoutError("_DoCommand")
TimeoutError: _DoCommand`

**Comment by Erdcgh** [comment]
Just so you know, I have had this working before, and I still now have an active wyze door sensor that working perfectly with my automatons. However I no longer have the option to to select the wyzesense.scan or wyzesense.delete service.

**Comment by aeckard87** [comment]
@Erdcgh - can you provide version of HA, if you're using Hassio or not, did you use HACS to install wyzesense or manually? Which version of wyzesense are you on?

**Comment by Erdcgh** [comment]
I have HASSIO ver. 0.97.2. I used the HACS to install wyzesense which is currently running at ver 0.0.6 but installed and was working with the version just before before that.

Thanks for the support!

**Comment by aeckard87** [comment]
:) Of course - I only just started tinkering with the abilities of this amazing implementation! Trying to find bugs is fun for me ;) 

Anyway, I did find this in previous issues as a work around: https://github.com/kevinvincent/ha-wyzesense/issues/29#issuecomment-532040719

Though with your setup this might be rather difficult, but it did shed some light on something you could try. And the fact that it was once working, and still working with an active door tells me this _might_ not be the case. So I did some reading...

I noted someone happened to discover one of their sensors was acting up and by chance they removed the battery, placed it back in, and things started functioning again. Another thing to consider is battery replacement. 

Was one of the first automatons I setup - alert on battery % below X.

Let me know if this helps! Best of luck

**Comment by Erdcgh** [comment]
Thanks aeckard87, but that is way to intense to have another VM running another service. Would like to see this instance of the software fixed.

Does anyone know how to manually add in a sensor if you already know its MAC address?

**Comment by mightymos** [comment]
There is an omission on the readme page here:
https://github.com/kevinvincent/ha-wyzesense
It omits the [binary_sensor:] portion for the YAML configuration file.

The video walk through shows the proper format:
https://www.youtube.com/watch?v=19UCwf4uidQ].

Good luck with the other issues.

**Comment by Erdcgh** [comment]
Thank you ever so much mightymos!

That did the trick for me.
