### ISSUE TITLE
Fixed: file does not exist .storage/wyze_sensors.txt

### ISSUE THREAD

**Issue by erlanger** [kevinvincent/ha-wyzesense#74]
The sensor was read only once, and not read anymore. The logs mention this error:

```
ERROR (Thread-3) [custom_components.wyzesense.wyzesense_custom] [Errno 2] No such file or directory: '.storage/wyze_sensors.txt'
```

After **creating the file** everything works okay, but this should be done directly in the code.

Thanks for the great work!

**Comment by erlanger** [comment]
by the way, I got the error again (missing `.storage/wyze_sensors.txt`), I think it is because the file is opened using a relative file name. Should probably include the directory, because it will cause problems if home assistant changes the running directory (`pwd`) for some reason.

**Comment by erlanger** [comment]
Update: I changed the code to use an absolute path and it works fine now.

**Comment by KingofTown** [comment]
Same issue for me. 

Note, this is a hassbian install, so ".storage/" is actually located at:
`/home/homeassistant/.homeassistant/.storage`

Tried adding the full path first, but all that did was get rid of the warning. The sensors were being discovered, but no wyze_storage.txt file was anywhere to be found. Nothing was working until I manually created the file.

**Comment by rodpayne** [comment]
I am new to Wyze Sensors and had this same problem when initially setting it up.  (The device appeared when it was first set up, but did not update after that.)  
**I reverted from release 0.0.6 to 0.0.5 and it started working wonderfully.**

**On the 0.0.6 release,** the log had:  `2019-12-29 21:54:09 ERROR (Thread-2) [custom_components.wyzesense.wyzesense_custom] [Errno 2] No such file or directory: '.storage/wyze_sensors.txt'`

Adding the file to /home/homeassistant/.homeassistant/.storage did not help.

**Comment by kevinvincent** [comment]
Hi all. Please update to `0.0.7` through HACS or the latest master. It will fix this issue specifically.
