### ISSUE TITLE
hidraw device not created after reboot without physically re-plugging the wyze hub

### ISSUE THREAD

**Issue by scottfuhrman** [kevinvincent/ha-wyzesense#77]
Anyone else having this issue? I don't believe it is directly related to this project, but if I reboot my computer with the Wyze hub plugged in, when it comes back up there is not a /dev/hidrawX device created.  If I unplug the Wyze hub then plug it back in, the device is created.

This means if my HA server reboots, I physically have to replug the device, then restart HA again to get the Wyze sensors functional.  If anyone has experienced this or has a solution I'd love to hear about it.

**Comment by bschatzow** [comment]
I have never had this issue. I have done several updates to my Hassio installation which a reboot was needed ( the latest was yesterday for a a HACS update). The Wyze components have always worked.

**Comment by scottfuhrman** [comment]
Thanks, wonder if it is something unique to my hardware (Supermicro E300-8D).

**Comment by scottfuhrman** [comment]
BTW I found the solution to my problem. Putting this here in case someone else runs into the same issue.

**Environment:**

- Debian Buster / Proxmox 6.1.3
- Supermicro E300-8D server

**Symptoms:**

- hidrawX device not created on system boot, but is created on hotplug of the Wyze usb hub.

- "device descriptor read/64, error -71" observed in dmesg during boot

**Solution:**

Put the following line in /etc/modprobe.d/options (and reboot to test)

`options usbcore use_both_schemes=y`

**Reasoning:**
Key is the -71 error when doing a read/64 to the device. Maybe Debian has a different default than others for usbcore?  Dunno, but it works now.

Reference & credit to these guys:
See detailed explanation: https://www.spinics.net/lists/usb/msg02644.html
Also credit to https://urukrama.wordpress.com/2009/01/27/usb-drive-not-recognised-error-71/
