### ISSUE TITLE
[Errno 110] Operation timed out

### ISSUE THREAD

**Issue by liquidzyklon** [kevinvincent/ha-wyzesense#78]
**Issue:** Will randomly get this error message for timing out. Can be long after rebooting or shortly after rebooting like this pastebin.
**Configuration:**
NUC running Virtualbox
Hass.IO on HassOS 2.11
Home Assistant Version 0.103.4
Installed HA-Wyzesense 0.0.6 from HACS
I do have six Wyze Sense sensors: 2 Motion, 4 contacts

My configuration.yaml lines are:
```
# Sensors
binary_sensor:
  - platform: wyzesense
    device: auto
    initial_state:
      # Motion Sensors, OFF = No Motion, On = Motion Detected
      778F7E19: "off"
      778F8C4C: "off"
      # Contact Sensors, Off = Closed, On = Opened
      778FFDCE: "off"
      778FFFCF: "off"
      77900C3D: "off"
      779014FF: "off"
```

https://pastebin.com/TYVktdkk

Log file attached
[home-assistant.log](https://github.com/kevinvincent/ha-wyzesense/files/4005756/home-assistant.log)

**Comment by liquidzyklon** [comment]
Here's a 2nd pastebin after running HA for some time before the Operations Time Out response.

https://pastebin.com/F71SxZna

**Comment by mattyb8562** [comment]
This is the same issue #20. There's a long discussion about it.

**Comment by liquidzyklon** [comment]
Thanks mattyb8562, I will close this issue to #20
