### ISSUE TITLE
Docker - Platform error binary_sensor.wyzesense - No module named 'retry'

### ISSUE THREAD

**Issue by devopsleigh** [kevinvincent/ha-wyzesense#82]
Running Home Assistant in Docker on RPi4.

Log:
```
Platform error binary_sensor.wyzesense - No module named 'retry'
9:28 AM components/homeassistant/__init__.py (ERROR)
```

Occurs after adding the following to the binary_sensors section of configuration.yaml:
```
- platform: wyzesense
  device: auto
```

Other solutions suggest editing `/etc/udev/rules.d/99-com.rules`, however this doesn't exist on my host or within the Docker container.

I assume the container won't have access to host devices without the `--device=/dev/whatever` argument anyway, so I may be missing some config.

**Comment by JFC-Dev** [comment]
There is an error in the documentation, "binary_sensor:" is missing in an example. You need to have:
binary_sensor:
  - platform: wyzesense
     device: auto

It might be the problem.

**Comment by hadynz** [comment]
I am having the same issue on my Rasberry Pi install.

[retry][1] is a dependency of ha-wyzesense as [per configuration][2]. Somehow, it is not being installed by hassio on restart.

[1]: https://pypi.org/project/retry/
[2]: https://github.com/kevinvincent/ha-wyzesense/blob/master/custom_components/wyzesense/manifest.json#L5

**Comment by kevinvincent** [comment]
How up to date is your HA install? The new dependency method was introduced somewhere in the low .90s which may be why it's failing to install it.

**Comment by hadynz** [comment]
I’m running version `0.100.2`. And the auto install doesn’t seem to be working. 

As a work around, what is the folder location in Hassio (raspberry pi) that I can use to manually install the `retry` dependency to test out this module?

**Comment by kevinvincent** [comment]
@hadynz Try sshing into Hassio and running `pip install retry`

**Comment by devopsleigh** [comment]
> 
> 
> @hadynz Try sshing into Hassio and running `pip install retry`
> 
> EDIT:
> Just kidding pip isn't available either. What you can do is edit `/custom_components/wyzesense/binary_sensor.py`. Just search for "retry" and delete the two lines that contain it. It's not super necessary.

Sorry I've not responded at all.

I'm still a few days away from being able to test this out, but it is consistent with what I was thinking. Thanks for responding in my absence.

**Comment by devopsleigh** [comment]
I updated everything and I've had no further issues. Thanks @kevinvincent.

**Comment by danecreekphotography** [comment]
I hit this same issue installing today on a RPI4. I commented out the two lines as suggested above and that resolved the problem.
