### ISSUE TITLE
what config files to backup and copy when migrating to a new host

### ISSUE THREAD

**Issue by nmsaini** [kevinvincent/ha-wyzesense#85]
I am planning on moving my HA instance to a docker environment. I will be using the same hardware device (/dev/hidraw). Is there a way to keep/migrate the configuration over without the need to do a "wyzesense.scan" to rediscover the sensors? Would like to save time from re-scanning the sensors!

Thanks!

**Comment by kevinvincent** [comment]
You will not have to backup anything.

With version 0.0.6 all data is stored on the dongle itself.

With version 0.0.7+, you will just have to re-trigger each sensor once connected to the new host to have the sensor show up again. It is just a one-time thing.
