### ISSUE TITLE
No hidraw showing up

### ISSUE THREAD

**Issue by tsalha** [kevinvincent/ha-wyzesense#87]
I'm a bit stumped and hoping someone can help as I haven't seen this pattern show up for anyone in the closed issues.  I have the add-on installed through HACS (NUC/Docker) and I've done the 99-com.rules update.  When I run dmesg | grep hidraw I don't see the Wyze as connected to the computer.  All I can see is my mouse and keyboard.  I've tried several USB ports.  The Wyze has a solid amber light.  Debug log --> https://pastebin.com/siG6nRcp

**Comment by kevinvincent** [comment]
Can you try the method in this issue: https://github.com/kevinvincent/ha-wyzesense/issues/66

**Comment by tsalha** [comment]
The below from that issue worked for me.  Thanks!

Create /etc/udev/rules.d/99-wyze.rules:
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="e024", SYMLINK+="wyzesense"
