### ISSUE TITLE
HACS failing to update to 0.0.7

### ISSUE THREAD

**Issue by bschatzow** [kevinvincent/ha-wyzesense#88]
HACS shows update available.  Tried to update, then restart several times.  Says Update .7 available.

**Comment by kevinvincent** [comment]
Can you try uninstalling and reinstalling via HACS?

**Comment by rxritalin** [comment]
Make sure you actually select the .7 install. 
I "updated" 3 times with each reboot showing that I still had an upgrade to install. 
Then I noticed that the drop-down for the version was not defaulting to the 0.7 install. (facepalm)

**Comment by bschatzow** [comment]
Mine says .7 and after it is done, it says a reboot is necessary.  I'll try an uninstall and reinstall when I return from my trip on Saturday and provide an update.

**Comment by kevinvincent** [comment]
This *sounds* like a HACS problem. Please be sure you're running the latest HACS as well. I've reviewed the HACS documentation and it seems like the releases are being correctly done and showing up in HACS.

You can verify if HACS has downloaded and installed the latest version by going to /custom_components/wyzesense/binary_sensor.py and checking if it says 0.0.7 at the top of the file.

**Comment by bschatzow** [comment]
Just returned home, updated HACS (again) then updated to .7 worked successfully.  You can now close this as I no longer have an issue.  Looks like it was a HACS problem.
