### ISSUE TITLE
I can't get the hub to load

### ISSUE THREAD

**Issue by whyitsbob** [kevinvincent/ha-wyzesense#93]
Hello I have installed HACS and added everything according to the instructions but I can't get the Hub to load so that I could add sensors. I am running HASSIO 0.104.3 on a Raspberry PI

My log shows
*********************
Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 76, in setup_platform
    _LOGGER.debug("Attempting to open connection to hub at " + config[CONF_DEVICE])
TypeError: can only concatenate str (not "NoneType") to str
*******************

My full log can be found at:  https://pastebin.com/mW28Am5N

Thank you so much for your help

**Comment by kevinvincent** [comment]
Can you post what you have in your config file?

**Comment by whyitsbob** [comment]
Sure

binary_sensor:
  - platforme: wyzesense
    device: auto

I also tried
    device: "/dev/hidraw0”
And
    device: "/dev/hidraw1”

The light never turns blue.

**Comment by kevinvincent** [comment]
can you shh into hassio and run `dmesg | grep hidraw` and post the result?

**Comment by whyitsbob** [comment]
~ $ dmesg | grep hidraw
[    0.868034] hidraw: raw HID events driver (C) Jiri Kosina
[    3.322760] hid-generic 0003:2222:0003.0001: input,hidraw0: USB HID v1.00 Keyboard [Macally Macally iKey     ] on usb-3f980000.usb-1.1.2.1/input0

**Comment by whyitsbob** [comment]
> Can you post what you have in your config file?

I also tried
binary_sensor:

platform: wyzesense
device: auto

**Comment by kevinvincent** [comment]
Interesting so hass.io isn't even finding the device. Try plugging the dongle into a different usb port. You can also try holding the button on the dongle (white square) for 10 seconds to reset it.

**Comment by oriolism** [comment]
I just had this problem and it looks like another usb device that was connected recently to my NUC was causing the problem.

**Comment by whyitsbob** [comment]
Problem solved. 
 Hass.io couldn’t find the hub because I had it connected to the Pi with a USB 3.0 cable because  the size of the hub blocks one of the ports. Once I plugged directly into the Pi and rebooted, it started working fine.  I’ve successfully  added sensors.   Thanks for all your help.

**Comment by kevinvincent** [comment]
You're welcome! Yeah, some people have had issues with USB extenders and the like.
