### ISSUE TITLE
I briefly saw in one post you were looking into a poll/refresh/sensor rate on detection

### ISSUE THREAD

**Issue by VarenDerpsAround** [kevinvincent/ha-wyzesense#94]
I didn't quite understand if you had come up with a way to set the refresh rate for just the wyze sensors lower. I didn't really need it persay, but as you put it "I feel like half a second [might make a difference] when it comes to automations."

hassos: 3.8
Plugin version: 0.0.7

Tried - 

Refresh Rate: 1 which worked but I couldn't notice a genuine difference
Refresh rate: 0.5 which did not work, resulted in error in the config, would not reboot

I will not try to do it with "0.5" instead, though I'm not sure if I've tried it as a string yet, likely won't work. if it's a string as refresh rate, then doing "1" would work, but 1 would just be turning it on like a boolean? or is there something I'm missing entirely. Before I put too much time into trying to get it to respond to my motion faster, wanted to know if I'm wasting my time. all locally controlled light bulbs as well, so, that rules out cloud interference.

**Comment by kevinvincent** [comment]
The wyze sensors don't actually poll so there isn't a refresh rate for this component.

This component is "local push" so as soon as the motion happens it will publish an event to home assistant which will update the entity. Theres a very small delay, most people think its practically instant though. Are you seeing a significant delay between motion being detected and the entity state updating?

**Comment by VarenDerpsAround** [comment]
No real reason why, so just go ahead and close this ticket. Wanted to know more about how the sensor worked and you responded wonderfully, thank you.
