### ISSUE TITLE
Sensors stopped working prior to 0.0.7 update.

### ISSUE THREAD

**Issue by DaveHenning** [kevinvincent/ha-wyzesense#96]
Have two motion and two door sensors. They stopped working a week or so ago, which prompted me to update to 0.0.7 but that didn't fix it. 

Three of the sensors do not even show up. "Entity not available" (also not in States).
One motion sensor does show up in HA but doesn't actually change on sensor activity. It is in states but always "off". 

I see the update note about retriggering the sensors. I assume that just means open a door / walk in front of a motion sensor. Of course I have tried that on all. 

Not sure where to go from here. 

Logs: https://pastebin.com/pDgTpbxY

Update: I just updated HA to 104.3 and now the one motion sensor is stuck in "on" instead of "off". All others still show as unavailable.

**Comment by photinus** [comment]
Have you tried pairing the sensors again?

**Comment by DaveHenning** [comment]
I did, for the one that still shows up, but I'm not 100% confident I did it correctly, because nothing happened. 

1. Went to `Developer Tools` > `Services`
2. Selected `wyzesense.scan`
3. Clicked `Call Service`, blue LED began blinking
4. Long pressed the button on the motion sensor until 3 (or 5?) red LED blinks.
5. Placed them within a few inches of each other and waited. Waited a few minutes. The blue sense LED never stopped blinking until after a reboot much later. 

The sensor is now always `on` instead of `off`

---

FWIW the update to 104.3 (from 103.x) was the reason for the update, in case that's relevant.

**Comment by DaveHenning** [comment]
Found a fix:

For anyone who runs into this, here's the steps I took. They might be over-kill but this is how I did it.

**A. Completely remove wyzesense from HA**

1. Uninstall Wyze Sense Component from HA
2. Reboot HA
3. Comment out wyzesense from config yaml
4. Reboot HA

*(probably can combine steps 1 - 4 into one reboot, but this is what I did to be ultra-sure)*

**B. Re-setup devices with Wyze Bridge**

5. Plug bridge back into Wyze Cam
6. Re-setup all sensors

**C. Bring it all back to HA**

7. Re-Install Wyze Sense Component to HA
8. Plug hub into USB port
9. Un-comment wyzesense in config yaml
10. Reboot HA
11. Manually trigger all sensors.
12. Fin
