### ISSUE TITLE
Upgrade to 0.0.7, devices are unavailable, wyzesense.scan and wysesense.remove services missing

### ISSUE THREAD

**Issue by DesertDwellerEv** [kevinvincent/ha-wyzesense#97]
Upgraded to 0.0.7 after upgrading HASSIO to the latest.
Went to rescan the devices by pairing the Wyze Sense devices to HA.
Services drop down no longer shows scan or remove commands.

**HASSIO**
_arch | aarch64
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | America/Phoenix
version | 0.104.3
virtualenv | false_

Log is attached
[home-assistant.log](https://github.com/kevinvincent/ha-wyzesense/files/4114900/home-assistant.log)
[home-assistant.log](https://github.com/kevinvincent/ha-wyzesense/files/4114902/home-assistant.log)

**Comment by kevinvincent** [comment]
Can you upload the file at `/config/.storage/wyzesense.json`?
Looks like it got corrupted somehow and the component is failing to load it.

**Comment by DesertDwellerEv** [comment]
Uninstalled ha-wyzesense.
Removed /config/.storage/wyzesense.json
Reinstalled and paired devices.
Seems to be working as expected.
Thanks.

**Comment by kevinvincent** [comment]
Great, not sure how that json file got corrupted as the component is the only thing that reads / writes to it. It is probably wise to make the component more resilient to file corruption so that it can automatically recover. That will go in the backlog.
